# coding: utf-8

"""
    Deployment API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AutoscalingRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scale_to_zero': 'AutoscalingRequestScaleToZero',
        'quantities': 'AutoscalingRequestQuantities',
        'metrics': 'list[AutoscalingRequestMetrics]'
    }

    attribute_map = {
        'scale_to_zero': 'scale_to_zero',
        'quantities': 'quantities',
        'metrics': 'metrics'
    }

    def __init__(self, scale_to_zero=None, quantities=None, metrics=None):  # noqa: E501
        """AutoscalingRequest - a model defined in Swagger"""  # noqa: E501
        self._scale_to_zero = None
        self._quantities = None
        self._metrics = None
        self.discriminator = None
        if scale_to_zero is not None:
            self.scale_to_zero = scale_to_zero
        if quantities is not None:
            self.quantities = quantities
        if metrics is not None:
            self.metrics = metrics

    @property
    def scale_to_zero(self):
        """Gets the scale_to_zero of this AutoscalingRequest.  # noqa: E501


        :return: The scale_to_zero of this AutoscalingRequest.  # noqa: E501
        :rtype: AutoscalingRequestScaleToZero
        """
        return self._scale_to_zero

    @scale_to_zero.setter
    def scale_to_zero(self, scale_to_zero):
        """Sets the scale_to_zero of this AutoscalingRequest.


        :param scale_to_zero: The scale_to_zero of this AutoscalingRequest.  # noqa: E501
        :type: AutoscalingRequestScaleToZero
        """

        self._scale_to_zero = scale_to_zero

    @property
    def quantities(self):
        """Gets the quantities of this AutoscalingRequest.  # noqa: E501


        :return: The quantities of this AutoscalingRequest.  # noqa: E501
        :rtype: AutoscalingRequestQuantities
        """
        return self._quantities

    @quantities.setter
    def quantities(self, quantities):
        """Sets the quantities of this AutoscalingRequest.


        :param quantities: The quantities of this AutoscalingRequest.  # noqa: E501
        :type: AutoscalingRequestQuantities
        """

        self._quantities = quantities

    @property
    def metrics(self):
        """Gets the metrics of this AutoscalingRequest.  # noqa: E501


        :return: The metrics of this AutoscalingRequest.  # noqa: E501
        :rtype: list[AutoscalingRequestMetrics]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this AutoscalingRequest.


        :param metrics: The metrics of this AutoscalingRequest.  # noqa: E501
        :type: list[AutoscalingRequestMetrics]
        """

        self._metrics = metrics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AutoscalingRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutoscalingRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
