# coding: utf-8

"""
    Deployment API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AutoscalingRequestMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metric_id': 'int',
        'parameters': 'list[AutoscalingRequestParameters]'
    }

    attribute_map = {
        'metric_id': 'metric_id',
        'parameters': 'parameters'
    }

    def __init__(self, metric_id=None, parameters=None):  # noqa: E501
        """AutoscalingRequestMetrics - a model defined in Swagger"""  # noqa: E501
        self._metric_id = None
        self._parameters = None
        self.discriminator = None
        if metric_id is not None:
            self.metric_id = metric_id
        if parameters is not None:
            self.parameters = parameters

    @property
    def metric_id(self):
        """Gets the metric_id of this AutoscalingRequestMetrics.  # noqa: E501


        :return: The metric_id of this AutoscalingRequestMetrics.  # noqa: E501
        :rtype: int
        """
        return self._metric_id

    @metric_id.setter
    def metric_id(self, metric_id):
        """Sets the metric_id of this AutoscalingRequestMetrics.


        :param metric_id: The metric_id of this AutoscalingRequestMetrics.  # noqa: E501
        :type: int
        """

        self._metric_id = metric_id

    @property
    def parameters(self):
        """Gets the parameters of this AutoscalingRequestMetrics.  # noqa: E501


        :return: The parameters of this AutoscalingRequestMetrics.  # noqa: E501
        :rtype: list[AutoscalingRequestParameters]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this AutoscalingRequestMetrics.


        :param parameters: The parameters of this AutoscalingRequestMetrics.  # noqa: E501
        :type: list[AutoscalingRequestParameters]
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AutoscalingRequestMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutoscalingRequestMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
