# coding: utf-8

"""
    Deployment API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PipelineUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'steps': 'list[PipelineStepUpdate]',
        'graph': 'PipelineGraph'
    }

    attribute_map = {
        'id': 'id',
        'steps': 'steps',
        'graph': 'graph'
    }

    def __init__(self, id=None, steps=None, graph=None):  # noqa: E501
        """PipelineUpdate - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._steps = None
        self._graph = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if steps is not None:
            self.steps = steps
        if graph is not None:
            self.graph = graph

    @property
    def id(self):
        """Gets the id of this PipelineUpdate.  # noqa: E501


        :return: The id of this PipelineUpdate.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PipelineUpdate.


        :param id: The id of this PipelineUpdate.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def steps(self):
        """Gets the steps of this PipelineUpdate.  # noqa: E501


        :return: The steps of this PipelineUpdate.  # noqa: E501
        :rtype: list[PipelineStepUpdate]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this PipelineUpdate.


        :param steps: The steps of this PipelineUpdate.  # noqa: E501
        :type: list[PipelineStepUpdate]
        """

        self._steps = steps

    @property
    def graph(self):
        """Gets the graph of this PipelineUpdate.  # noqa: E501


        :return: The graph of this PipelineUpdate.  # noqa: E501
        :rtype: PipelineGraph
        """
        return self._graph

    @graph.setter
    def graph(self, graph):
        """Sets the graph of this PipelineUpdate.


        :param graph: The graph of this PipelineUpdate.  # noqa: E501
        :type: PipelineGraph
        """

        self._graph = graph

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PipelineUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
