# coding: utf-8

"""
    Deployment API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PipelineCreateStepCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'model_version_id': 'int',
        'attributes': 'PipelineStepAttributes'
    }

    attribute_map = {
        'name': 'name',
        'model_version_id': 'model_version_id',
        'attributes': 'attributes'
    }

    def __init__(self, name=None, model_version_id=None, attributes=None):  # noqa: E501
        """PipelineCreateStepCreate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._model_version_id = None
        self._attributes = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if model_version_id is not None:
            self.model_version_id = model_version_id
        if attributes is not None:
            self.attributes = attributes

    @property
    def name(self):
        """Gets the name of this PipelineCreateStepCreate.  # noqa: E501


        :return: The name of this PipelineCreateStepCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PipelineCreateStepCreate.


        :param name: The name of this PipelineCreateStepCreate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def model_version_id(self):
        """Gets the model_version_id of this PipelineCreateStepCreate.  # noqa: E501


        :return: The model_version_id of this PipelineCreateStepCreate.  # noqa: E501
        :rtype: int
        """
        return self._model_version_id

    @model_version_id.setter
    def model_version_id(self, model_version_id):
        """Sets the model_version_id of this PipelineCreateStepCreate.


        :param model_version_id: The model_version_id of this PipelineCreateStepCreate.  # noqa: E501
        :type: int
        """

        self._model_version_id = model_version_id

    @property
    def attributes(self):
        """Gets the attributes of this PipelineCreateStepCreate.  # noqa: E501


        :return: The attributes of this PipelineCreateStepCreate.  # noqa: E501
        :rtype: PipelineStepAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this PipelineCreateStepCreate.


        :param attributes: The attributes of this PipelineCreateStepCreate.  # noqa: E501
        :type: PipelineStepAttributes
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PipelineCreateStepCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineCreateStepCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
