version: 2

build:
  tools:
    python: "3"

python:
  install:
  - method: pip
    path: client/verta
  - requirements: client/verta/docs/requirements.txt

sphinx:
  builder: html
  configuration: client/verta/docs/conf.py
  fail_on_warning: true
