# build environment

FROM node:9.6.1 as builder
# Create working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Install required package dependencies
COPY package.json /usr/src/app/package.json
RUN npm install --silent

# Copy app source
COPY . /usr/src/app
RUN npm run build

# production environment

FROM nginx:1.13.9-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


