ARG BASE_IMAGE=adoptopenjdk/openjdk16:jdk-16_36-alpine
FROM $BASE_IMAGE

RUN mkdir -p modeldb-project-work-dir
WORKDIR /modeldb-project-work-dir

COPY server/target/modeldb-1.0-SNAPSHOT-client-build.jar modeldb-1.0-SNAPSHOT-client-build.jar

# Define environment variable
ENV NAME modeldb-backend
ENV VERTA_MODELDB_CONFIG /config/config.yaml


ENTRYPOINT ["java"]
CMD ["-jar", "modeldb-1.0-SNAPSHOT-client-build.jar"]
