apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    component: webapp
  name: {{ .Release.Name }}-webapp
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}
    component: webapp
  type: ClusterIP
