apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeldb
  name: modeldb-frontend
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.image.modeldbFrontendImage}}
        name: modeldb-frontend
        env:
          - name:  DEPLOYED
            value:  "yes"
          - name: BACKEND_API_PROTOCOL
            value: "http"
          - name: BACKEND_API_DOMAIN
            value: "modeldb-backend-proxy:8080"
          - name: MDB_ADDRESS
            value: http://modeldb-backend-proxy:8080
          - name: ARTIFACTORY_ADDRESS
            value: http://modeldb-backend:8086
          - name: GQL_ADDRESS
            value: http://modeldb-graphql:4000
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
