apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: modeldb
  name: modeldb-graphql
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  selector:
    app: modeldb
    tier: graphql
  type: ClusterIP
