apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeldb
  name: modeldb-graphql
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: graphql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: graphql
    spec:
      containers:
      - image: {{ .Values.image.modeldbGraphqlImage}}
        name: modeldb-graphql
        env:
          - name:  DEPLOYED
            value:  "yes"
          - name: BACKEND_API_PROTOCOL
            value: "http"
          - name: BACKEND_API_DOMAIN
            value: "modeldb-backend-proxy:8080"
          - name: MDB_ADDRESS
            value: http://modeldb-backend-proxy:8080
          - name: ARTIFACTORY_ADDRESS
            value: http://modeldb-backend:8086
        ports:
        - containerPort: 3000
