apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: modeldb
  name: postgres
spec:
  serviceName: "modeldb-postgres"
  selector:
    matchLabels:
      app: modeldb
      tier: postgres
  template:
    metadata:
      labels:
        app: modeldb
        tier: postgres
    spec:
      containers:
      - name: modeldb-backend-postgres
        image: {{ .Values.image.modeldbDatabaseImage }}
        env:
        - name: POSTGRES_PASSWORD
          value: root
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.modeldbPostgresPvcSize }}
