{{ if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-backend
spec:
  maxUnavailable: 20%
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: backend
{{ end }}
