apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    component: backend
  name: {{ .Release.Name }}-backend
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - name: backend
      port: 8085
    - name: artifactstore
      port: 8086
    - port: 3000
      name: http
  selector:
    app: {{ .Release.Name }}
    component: backend
  type: ClusterIP
