{{- if .Values.artifactStore.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}
    component: backend
{{- if .Values.labels}}
{{toYaml .Values.labels | indent 4 -}}
{{- end}}
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: backend
  serviceName: {{ .Release.Name }}-headless
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: backend
{{- if .Values.labels}}
{{toYaml .Values.labels | indent 8 -}}
{{- end}}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        verta.ai/disable_anti_affinity: "true"
    spec:
{{- if .Values.securityContext.enabled }}
      securityContext:
        {{- if .Values.securityContext.runAsUser }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        {{- end}}
        {{- if .Values.securityContext.fsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        {{- end}}
{{- end}}
      containers:
        - image: {{ .Values.image }}:{{ .Values.imageTag }}
          env:
            - name: VERTA_MODELDB_CONFIG
              value: /config-backend/config.yaml
            {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8085
              name: backend
            - containerPort:  8086
              name: artifactstore
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8085", "-service=ready"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8085", "-service=live"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 15
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "sleep 10",
                ]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - mountPath: /config-backend
              name: {{ .Release.Name }}-secret-volume
              readOnly: true
            - mountPath: "{{ .Values.artifactStore.path }}"
              name: {{ .Release.Name }}
              subPath: {{ .Values.artifactStore.subPath }}
        - image: {{ .Values.proxy.image }}:{{ .Values.proxy.imageTag }}
          imagePullPolicy: Always
          name: proxy
          env:
            - name: MDB_ADDRESS
              value: localhost:8085
            - name: SERVER_HTTP_PORT
              value: "3000"
            {{- range $name, $value := .Values.proxy.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 3000
              name: http
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{ if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-secret-volume
          secret:
            secretName: {{ .Release.Name }}-backend-config-secret
{{- if .Values.artifactStore.existingClaim }}
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
{{- with .Values.artifactStore.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- end }}
{{- if not .Values.artifactStore.existingClaim }}
  volumeClaimTemplates:
  - metadata:
      labels:
        app: {{ .Release.Name }}
        component: backend
      name: {{ .Release.Name }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "{{ .Values.artifactStore.storage }}"
{{- end }}
{{- end -}}
