alter table artifact drop constraint FKb1510ajwbgmwqk9mk7s5madq8;
alter table artifact drop constraint FKkxd7ammk6wfh5sornvyqmwa6o;
alter table artifact drop constraint FKqi7jpmsvst8h67mvp18lrkdol;
alter table attribute drop constraint FKnt3ngg343dg4o7sven04h7tsx;
alter table attribute drop constraint FKc3dbivps61eg0k4pj8yvii3or;
alter table attribute drop constraint FKe0vuckk3jedm4r8aje7jiuqad;
alter table attribute drop constraint FKriiu1tqwndsykgh7mnmhx361v;
alter table attribute drop constraint FK2v3aix0o075acj0f29d38mewg;
alter table attribute drop constraint FK5kbo2i8a4hjtwrme7ii0q55xs;
alter table codeversion drop constraint FK52kol2q55s4ih48da63mshmua;
alter table codeversion drop constraint FKlmregkintq62cstaboy0b8mgv;
alter table collaboratorMappings drop constraint FKlysef6ksenp6fssh0gi7762u7;
alter table collaboratorMappings drop constraint FK6wxqhkm0t7jj81ra7cyo0ro67;
alter table dataset_part_info drop constraint FKglp4vghk1s78vudr9jnmvt7v2;
alter table datasetversion drop constraint FKqegkomuovtkr5iwqiqmav067;
alter table datasetversion drop constraint FK63372a2omdh2kx9bo7xifm13l;
alter table datasetversion drop constraint FK4axpq0odnw6n9yhom6kg0p0bw;
alter table experiment drop constraint FKabmp29pv19fw9g3rotaq4bqlk;
alter table experimentRun drop constraint FK155a2dpu2yc6kpbnf9bw9ej9e;
alter table Feature drop constraint FK1809dxglqgape7roab6ppb5pj;
alter table Feature drop constraint FK7npjb7lsh1lnc5sjfs5go1q9k;
alter table Feature drop constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc;
alter table Feature drop constraint FKiixqgx81l0gco5buvig6cqe2e;
alter table GitSnapshotEntity_filepaths drop constraint FKabgd4u299tnae1u81fnxtx4wg;
alter table keyvalue drop constraint FKe5e22km3s8b4v6fmd5agi1169;
alter table keyvalue drop constraint FKaotbvffphusp2xibg54y1807c;
alter table keyvalue drop constraint FKs8b954cb584lfhxvpfqufp00c;
alter table keyvalue drop constraint FKdd3gul9rqi1nwo1ue8dnjkloi;
alter table keyvalue drop constraint FK1j6qxx2f4tu0vhk6ncoigcer1;
alter table keyvalue drop constraint FK4kpjcj5k42wy7jixlaw69t39e;
alter table observation drop constraint FKqukq600uk7ow0smk86lbecm16;
alter table observation drop constraint FKlphf7x2yos9jxj1dafev0woqp;
alter table observation drop constraint FKrtaesogbnqbnfcg4r9oug3b5p;
alter table observation drop constraint FK3l830ric355y2m15auy29nugd;
alter table observation drop constraint FKtng8v4k62d498u95g3cly1dcp;
alter table project drop constraint FK7h4kclvrdgs3rp838yoj0utc4;
alter table query_parameter drop constraint FK8ocpexp2jn9rqlf2loy36pwpu;
alter table TagMapping drop constraint FKo3adl5c9mq66v4btyl9wwmbh;
alter table TagMapping drop constraint FKcsd9g3kgclunkjsigfn15pnl2;
alter table TagMapping drop constraint FK6don0cq34v6j75a6ddvfft5mq;
alter table TagMapping drop constraint FK7qfxoshi1y5vnn42yvxklr7hm;
alter table TagMapping drop constraint FKht136fxcojwibhx48k7iolc1u;
alter table user_comment drop constraint FK8run8dgvadrrwcwe5xpdscynm;
drop table if exists artifact cascade;
drop table if exists artifactStore cascade;
drop table if exists attribute cascade;
drop table if exists codeversion cascade;
drop table if exists collaborator cascade;
drop table if exists collaboratorMappings cascade;
drop table if exists comment cascade;
drop table if exists dataset cascade;
drop table if exists dataset_part_info cascade;
drop table if exists datasetversion cascade;
drop table if exists experiment cascade;
drop table if exists experimentRun cascade;
drop table if exists Feature cascade;
drop table if exists gitsnapshot cascade;
drop table if exists GitSnapshotEntity_filepaths cascade;
drop table if exists job cascade;
drop table if exists keyvalue cascade;
drop table if exists observation cascade;
drop table if exists path_dataset_version_info cascade;
drop table if exists project cascade;
drop table if exists query_dataset_version_info cascade;
drop table if exists query_parameter cascade;
drop table if exists raw_dataset_version_info cascade;
drop table if exists TagMapping cascade;
drop table if exists user_comment cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table artifact (id int8 not null, artifact_type int4, entity_name varchar(50), field_type varchar(50), filename_extension varchar(50), ar_key TEXT, linked_artifact_id varchar(255), ar_path TEXT, path_only boolean, store_type_path TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table artifactStore (id int8 not null, client_key TEXT, cloud_storage_file_path TEXT, cloud_storage_key TEXT, entity_id varchar(50), entity_name varchar(50), primary key (id));
create table attribute (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table codeversion (id int8 not null, date_logged int8, field_type varchar(50), code_archive_id int8, git_snapshot_id int8, primary key (id));
create table collaborator (verta_id varchar(255) not null, email_id varchar(255), share_via_type int4, user_id varchar(255), primary key (verta_id));
create table collaboratorMappings (id int8 not null, collaborator_type int4, date_created int8, date_deleted int8, date_updated int8, entity_id varchar(255), entity_name varchar(50), field_type varchar(50), message varchar(255), shared_by varchar(255), collaborator_id varchar(255), collaborator_verta_id varchar(255), primary key (id));
create table comment (id varchar(255) not null, entity_id varchar(255), entity_name varchar(255), primary key (id));
create table dataset (id varchar(255) not null, dataset_type int4, dataset_visibility int4, description TEXT, name varchar(255), owner varchar(255), time_created int8, time_updated int8, primary key (id));
create table dataset_part_info (id int8 not null, checksum varchar(255), entity_name varchar(50), field_type varchar(50), last_modified_at_source int8, path varchar(255), size int8, path_dataset_version_info_id int8, primary key (id));
create table datasetversion (id varchar(255) not null, dataset_id varchar(255), dataset_type int4, dataset_version_visibility int4, description TEXT, owner varchar(255), parent_id varchar(255), time_logged int8, time_updated int8, version int8, path_dataset_version_info_id int8, query_dataset_version_info_id int8, raw_dataset_version_info_id int8, primary key (id));
create table experiment (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_id varchar(255) not null, code_version_snapshot_id int8, primary key (id));
create table experimentRun (id varchar(255) not null, code_version varchar(255), date_created int8, date_updated int8, description TEXT, end_time int8, experiment_id varchar(255) not null, job_id varchar(255), name varchar(255), owner varchar(255), parent_id varchar(255), project_id varchar(255) not null, start_time int8, code_version_snapshot_id int8, primary key (id));
create table Feature (id int8 not null, entity_name varchar(50), feature TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), raw_dataset_version_info_id int8, primary key (id));
create table gitsnapshot (id int8 not null, field_type varchar(50), hash varchar(255), is_dirty int4, repo varchar(255), primary key (id));
create table GitSnapshotEntity_filepaths (GitSnapshotEntity_id int8 not null, filepaths varchar(255));
create table job (id varchar(255) not null, description TEXT, end_time varchar(255), job_status int4, job_type int4, owner varchar(255), start_time varchar(255), primary key (id));
create table keyvalue (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table observation (id int8 not null, entity_name varchar(50), field_type varchar(50), timestamp int8 not null, artifact_id int8, experiment_id varchar(255), experiment_run_id varchar(255), keyValueMapping_id int8, project_id varchar(255), primary key (id));
create table path_dataset_version_info (id int8 not null, base_path varchar(255), field_type varchar(50), location_type int4, size int8, primary key (id));
create table project (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_visibility int4, readme_text TEXT, short_name varchar(255), code_version_snapshot_id int8, primary key (id));
create table query_dataset_version_info (id int8 not null, data_source_uri varchar(255), execution_timestamp int8, field_type varchar(50), num_records int8, query TEXT, query_template TEXT, primary key (id));
create table query_parameter (id int8 not null, entity_name varchar(50), field_type varchar(50), parameter_name TEXT, parameter_type int4, parameter_value TEXT, query_dataset_version_info_id int8, primary key (id));
create table raw_dataset_version_info (id int8 not null, checksum varchar(255), field_type varchar(50), num_records int8, object_path varchar(255), size int8, primary key (id));
create table TagMapping (id int8 not null, entity_name varchar(50), tags TEXT, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table user_comment (id varchar(255) not null, date_time int8, entity_name varchar(50), message varchar(255), owner varchar(255), user_id varchar(255), comment_id varchar(255), primary key (id));
alter table collaborator add constraint UK_knalm74v0noabmm15ya57ctbt unique (user_id);
alter table artifact add constraint FKb1510ajwbgmwqk9mk7s5madq8 foreign key (experiment_id) references experiment;
alter table artifact add constraint FKkxd7ammk6wfh5sornvyqmwa6o foreign key (experiment_run_id) references experimentRun;
alter table artifact add constraint FKqi7jpmsvst8h67mvp18lrkdol foreign key (project_id) references project;
alter table attribute add constraint FKnt3ngg343dg4o7sven04h7tsx foreign key (dataset_id) references dataset;
alter table attribute add constraint FKc3dbivps61eg0k4pj8yvii3or foreign key (dataset_version_id) references datasetversion;
alter table attribute add constraint FKe0vuckk3jedm4r8aje7jiuqad foreign key (experiment_id) references experiment;
alter table attribute add constraint FKriiu1tqwndsykgh7mnmhx361v foreign key (experiment_run_id) references experimentRun;
alter table attribute add constraint FK2v3aix0o075acj0f29d38mewg foreign key (job_id) references job;
alter table attribute add constraint FK5kbo2i8a4hjtwrme7ii0q55xs foreign key (project_id) references project;
alter table codeversion add constraint FK52kol2q55s4ih48da63mshmua foreign key (code_archive_id) references artifact;
alter table codeversion add constraint FKlmregkintq62cstaboy0b8mgv foreign key (git_snapshot_id) references gitsnapshot;
alter table collaboratorMappings add constraint FKlysef6ksenp6fssh0gi7762u7 foreign key (collaborator_id) references collaborator;
alter table collaboratorMappings add constraint FK6wxqhkm0t7jj81ra7cyo0ro67 foreign key (collaborator_verta_id) references collaborator;
alter table dataset_part_info add constraint FKglp4vghk1s78vudr9jnmvt7v2 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FKqegkomuovtkr5iwqiqmav067 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FK63372a2omdh2kx9bo7xifm13l foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table datasetversion add constraint FK4axpq0odnw6n9yhom6kg0p0bw foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table experiment add constraint FKabmp29pv19fw9g3rotaq4bqlk foreign key (code_version_snapshot_id) references codeversion;
alter table experimentRun add constraint FK155a2dpu2yc6kpbnf9bw9ej9e foreign key (code_version_snapshot_id) references codeversion;
alter table Feature add constraint FK1809dxglqgape7roab6ppb5pj foreign key (experiment_id) references experiment;
alter table Feature add constraint FK7npjb7lsh1lnc5sjfs5go1q9k foreign key (experiment_run_id) references experimentRun;
alter table Feature add constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc foreign key (project_id) references project;
alter table Feature add constraint FKiixqgx81l0gco5buvig6cqe2e foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table GitSnapshotEntity_filepaths add constraint FKabgd4u299tnae1u81fnxtx4wg foreign key (GitSnapshotEntity_id) references gitsnapshot;
alter table keyvalue add constraint FKe5e22km3s8b4v6fmd5agi1169 foreign key (dataset_id) references dataset;
alter table keyvalue add constraint FKaotbvffphusp2xibg54y1807c foreign key (dataset_version_id) references datasetversion;
alter table keyvalue add constraint FKs8b954cb584lfhxvpfqufp00c foreign key (experiment_id) references experiment;
alter table keyvalue add constraint FKdd3gul9rqi1nwo1ue8dnjkloi foreign key (experiment_run_id) references experimentRun;
alter table keyvalue add constraint FK1j6qxx2f4tu0vhk6ncoigcer1 foreign key (job_id) references job;
alter table keyvalue add constraint FK4kpjcj5k42wy7jixlaw69t39e foreign key (project_id) references project;
alter table observation add constraint FKqukq600uk7ow0smk86lbecm16 foreign key (artifact_id) references artifact;
alter table observation add constraint FKlphf7x2yos9jxj1dafev0woqp foreign key (experiment_id) references experiment;
alter table observation add constraint FKrtaesogbnqbnfcg4r9oug3b5p foreign key (experiment_run_id) references experimentRun;
alter table observation add constraint FK3l830ric355y2m15auy29nugd foreign key (keyValueMapping_id) references keyvalue;
alter table observation add constraint FKtng8v4k62d498u95g3cly1dcp foreign key (project_id) references project;
alter table project add constraint FK7h4kclvrdgs3rp838yoj0utc4 foreign key (code_version_snapshot_id) references codeversion;
alter table query_parameter add constraint FK8ocpexp2jn9rqlf2loy36pwpu foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table TagMapping add constraint FKo3adl5c9mq66v4btyl9wwmbh foreign key (dataset_id) references dataset;
alter table TagMapping add constraint FKcsd9g3kgclunkjsigfn15pnl2 foreign key (dataset_version_id) references datasetversion;
alter table TagMapping add constraint FK6don0cq34v6j75a6ddvfft5mq foreign key (experiment_id) references experiment;
alter table TagMapping add constraint FK7qfxoshi1y5vnn42yvxklr7hm foreign key (experiment_run_id) references experimentRun;
alter table TagMapping add constraint FKht136fxcojwibhx48k7iolc1u foreign key (project_id) references project;
alter table user_comment add constraint FK8run8dgvadrrwcwe5xpdscynm foreign key (comment_id) references comment;
alter table artifact drop constraint FKb1510ajwbgmwqk9mk7s5madq8;
alter table artifact drop constraint FKkxd7ammk6wfh5sornvyqmwa6o;
alter table artifact drop constraint FKqi7jpmsvst8h67mvp18lrkdol;
alter table attribute drop constraint FKnt3ngg343dg4o7sven04h7tsx;
alter table attribute drop constraint FKc3dbivps61eg0k4pj8yvii3or;
alter table attribute drop constraint FKe0vuckk3jedm4r8aje7jiuqad;
alter table attribute drop constraint FKriiu1tqwndsykgh7mnmhx361v;
alter table attribute drop constraint FK2v3aix0o075acj0f29d38mewg;
alter table attribute drop constraint FK5kbo2i8a4hjtwrme7ii0q55xs;
alter table codeversion drop constraint FK52kol2q55s4ih48da63mshmua;
alter table codeversion drop constraint FKlmregkintq62cstaboy0b8mgv;
alter table collaboratorMappings drop constraint FKlysef6ksenp6fssh0gi7762u7;
alter table collaboratorMappings drop constraint FK6wxqhkm0t7jj81ra7cyo0ro67;
alter table dataset_part_info drop constraint FKglp4vghk1s78vudr9jnmvt7v2;
alter table datasetversion drop constraint FKqegkomuovtkr5iwqiqmav067;
alter table datasetversion drop constraint FK63372a2omdh2kx9bo7xifm13l;
alter table datasetversion drop constraint FK4axpq0odnw6n9yhom6kg0p0bw;
alter table experiment drop constraint FKabmp29pv19fw9g3rotaq4bqlk;
alter table experimentRun drop constraint FK155a2dpu2yc6kpbnf9bw9ej9e;
alter table Feature drop constraint FK1809dxglqgape7roab6ppb5pj;
alter table Feature drop constraint FK7npjb7lsh1lnc5sjfs5go1q9k;
alter table Feature drop constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc;
alter table Feature drop constraint FKiixqgx81l0gco5buvig6cqe2e;
alter table GitSnapshotEntity_filepaths drop constraint FKabgd4u299tnae1u81fnxtx4wg;
alter table keyvalue drop constraint FKe5e22km3s8b4v6fmd5agi1169;
alter table keyvalue drop constraint FKaotbvffphusp2xibg54y1807c;
alter table keyvalue drop constraint FKs8b954cb584lfhxvpfqufp00c;
alter table keyvalue drop constraint FKdd3gul9rqi1nwo1ue8dnjkloi;
alter table keyvalue drop constraint FK1j6qxx2f4tu0vhk6ncoigcer1;
alter table keyvalue drop constraint FK4kpjcj5k42wy7jixlaw69t39e;
alter table observation drop constraint FKqukq600uk7ow0smk86lbecm16;
alter table observation drop constraint FKlphf7x2yos9jxj1dafev0woqp;
alter table observation drop constraint FKrtaesogbnqbnfcg4r9oug3b5p;
alter table observation drop constraint FK3l830ric355y2m15auy29nugd;
alter table observation drop constraint FKtng8v4k62d498u95g3cly1dcp;
alter table project drop constraint FK7h4kclvrdgs3rp838yoj0utc4;
alter table query_parameter drop constraint FK8ocpexp2jn9rqlf2loy36pwpu;
alter table TagMapping drop constraint FKo3adl5c9mq66v4btyl9wwmbh;
alter table TagMapping drop constraint FKcsd9g3kgclunkjsigfn15pnl2;
alter table TagMapping drop constraint FK6don0cq34v6j75a6ddvfft5mq;
alter table TagMapping drop constraint FK7qfxoshi1y5vnn42yvxklr7hm;
alter table TagMapping drop constraint FKht136fxcojwibhx48k7iolc1u;
alter table user_comment drop constraint FK8run8dgvadrrwcwe5xpdscynm;
drop table if exists artifact cascade;
drop table if exists artifactStore cascade;
drop table if exists attribute cascade;
drop table if exists codeversion cascade;
drop table if exists collaborator cascade;
drop table if exists collaboratorMappings cascade;
drop table if exists comment cascade;
drop table if exists dataset cascade;
drop table if exists dataset_part_info cascade;
drop table if exists datasetversion cascade;
drop table if exists experiment cascade;
drop table if exists experimentRun cascade;
drop table if exists Feature cascade;
drop table if exists gitsnapshot cascade;
drop table if exists GitSnapshotEntity_filepaths cascade;
drop table if exists job cascade;
drop table if exists keyvalue cascade;
drop table if exists observation cascade;
drop table if exists path_dataset_version_info cascade;
drop table if exists project cascade;
drop table if exists query_dataset_version_info cascade;
drop table if exists query_parameter cascade;
drop table if exists raw_dataset_version_info cascade;
drop table if exists TagMapping cascade;
drop table if exists user_comment cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table artifact (id int8 not null, artifact_type int4, entity_name varchar(50), field_type varchar(50), filename_extension varchar(50), ar_key TEXT, linked_artifact_id varchar(255), ar_path TEXT, path_only boolean, store_type_path TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table artifactStore (id int8 not null, client_key TEXT, cloud_storage_file_path TEXT, cloud_storage_key TEXT, entity_id varchar(50), entity_name varchar(50), primary key (id));
create table attribute (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table codeversion (id int8 not null, date_logged int8, field_type varchar(50), code_archive_id int8, git_snapshot_id int8, primary key (id));
create table collaborator (verta_id varchar(255) not null, email_id varchar(255), share_via_type int4, user_id varchar(255), primary key (verta_id));
create table collaboratorMappings (id int8 not null, collaborator_type int4, date_created int8, date_deleted int8, date_updated int8, entity_id varchar(255), entity_name varchar(50), field_type varchar(50), message varchar(255), shared_by varchar(255), collaborator_id varchar(255), collaborator_verta_id varchar(255), primary key (id));
create table comment (id varchar(255) not null, entity_id varchar(255), entity_name varchar(255), primary key (id));
create table dataset (id varchar(255) not null, dataset_type int4, dataset_visibility int4, description TEXT, name varchar(255), owner varchar(255), time_created int8, time_updated int8, primary key (id));
create table dataset_part_info (id int8 not null, checksum varchar(255), entity_name varchar(50), field_type varchar(50), last_modified_at_source int8, path varchar(255), size int8, path_dataset_version_info_id int8, primary key (id));
create table datasetversion (id varchar(255) not null, dataset_id varchar(255), dataset_type int4, dataset_version_visibility int4, description TEXT, owner varchar(255), parent_id varchar(255), time_logged int8, time_updated int8, version int8, path_dataset_version_info_id int8, query_dataset_version_info_id int8, raw_dataset_version_info_id int8, primary key (id));
create table experiment (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_id varchar(255) not null, code_version_snapshot_id int8, primary key (id));
create table experimentRun (id varchar(255) not null, code_version varchar(255), date_created int8, date_updated int8, description TEXT, end_time int8, experiment_id varchar(255) not null, job_id varchar(255), name varchar(255), owner varchar(255), parent_id varchar(255), project_id varchar(255) not null, start_time int8, code_version_snapshot_id int8, primary key (id));
create table Feature (id int8 not null, entity_name varchar(50), feature TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), raw_dataset_version_info_id int8, primary key (id));
create table gitsnapshot (id int8 not null, field_type varchar(50), hash varchar(255), is_dirty int4, repo varchar(255), primary key (id));
create table GitSnapshotEntity_filepaths (GitSnapshotEntity_id int8 not null, filepaths varchar(255));
create table job (id varchar(255) not null, description TEXT, end_time varchar(255), job_status int4, job_type int4, owner varchar(255), start_time varchar(255), primary key (id));
create table keyvalue (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table observation (id int8 not null, entity_name varchar(50), field_type varchar(50), timestamp int8 not null, artifact_id int8, experiment_id varchar(255), experiment_run_id varchar(255), keyValueMapping_id int8, project_id varchar(255), primary key (id));
create table path_dataset_version_info (id int8 not null, base_path varchar(255), field_type varchar(50), location_type int4, size int8, primary key (id));
create table project (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_visibility int4, readme_text TEXT, short_name varchar(255), code_version_snapshot_id int8, primary key (id));
create table query_dataset_version_info (id int8 not null, data_source_uri varchar(255), execution_timestamp int8, field_type varchar(50), num_records int8, query TEXT, query_template TEXT, primary key (id));
create table query_parameter (id int8 not null, entity_name varchar(50), field_type varchar(50), parameter_name TEXT, parameter_type int4, parameter_value TEXT, query_dataset_version_info_id int8, primary key (id));
create table raw_dataset_version_info (id int8 not null, checksum varchar(255), field_type varchar(50), num_records int8, object_path varchar(255), size int8, primary key (id));
create table TagMapping (id int8 not null, entity_name varchar(50), tags TEXT, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table user_comment (id varchar(255) not null, date_time int8, entity_name varchar(50), message varchar(255), owner varchar(255), user_id varchar(255), comment_id varchar(255), primary key (id));
alter table collaborator add constraint UK_knalm74v0noabmm15ya57ctbt unique (user_id);
alter table artifact add constraint FKb1510ajwbgmwqk9mk7s5madq8 foreign key (experiment_id) references experiment;
alter table artifact add constraint FKkxd7ammk6wfh5sornvyqmwa6o foreign key (experiment_run_id) references experimentRun;
alter table artifact add constraint FKqi7jpmsvst8h67mvp18lrkdol foreign key (project_id) references project;
alter table attribute add constraint FKnt3ngg343dg4o7sven04h7tsx foreign key (dataset_id) references dataset;
alter table attribute add constraint FKc3dbivps61eg0k4pj8yvii3or foreign key (dataset_version_id) references datasetversion;
alter table attribute add constraint FKe0vuckk3jedm4r8aje7jiuqad foreign key (experiment_id) references experiment;
alter table attribute add constraint FKriiu1tqwndsykgh7mnmhx361v foreign key (experiment_run_id) references experimentRun;
alter table attribute add constraint FK2v3aix0o075acj0f29d38mewg foreign key (job_id) references job;
alter table attribute add constraint FK5kbo2i8a4hjtwrme7ii0q55xs foreign key (project_id) references project;
alter table codeversion add constraint FK52kol2q55s4ih48da63mshmua foreign key (code_archive_id) references artifact;
alter table codeversion add constraint FKlmregkintq62cstaboy0b8mgv foreign key (git_snapshot_id) references gitsnapshot;
alter table collaboratorMappings add constraint FKlysef6ksenp6fssh0gi7762u7 foreign key (collaborator_id) references collaborator;
alter table collaboratorMappings add constraint FK6wxqhkm0t7jj81ra7cyo0ro67 foreign key (collaborator_verta_id) references collaborator;
alter table dataset_part_info add constraint FKglp4vghk1s78vudr9jnmvt7v2 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FKqegkomuovtkr5iwqiqmav067 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FK63372a2omdh2kx9bo7xifm13l foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table datasetversion add constraint FK4axpq0odnw6n9yhom6kg0p0bw foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table experiment add constraint FKabmp29pv19fw9g3rotaq4bqlk foreign key (code_version_snapshot_id) references codeversion;
alter table experimentRun add constraint FK155a2dpu2yc6kpbnf9bw9ej9e foreign key (code_version_snapshot_id) references codeversion;
alter table Feature add constraint FK1809dxglqgape7roab6ppb5pj foreign key (experiment_id) references experiment;
alter table Feature add constraint FK7npjb7lsh1lnc5sjfs5go1q9k foreign key (experiment_run_id) references experimentRun;
alter table Feature add constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc foreign key (project_id) references project;
alter table Feature add constraint FKiixqgx81l0gco5buvig6cqe2e foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table GitSnapshotEntity_filepaths add constraint FKabgd4u299tnae1u81fnxtx4wg foreign key (GitSnapshotEntity_id) references gitsnapshot;
alter table keyvalue add constraint FKe5e22km3s8b4v6fmd5agi1169 foreign key (dataset_id) references dataset;
alter table keyvalue add constraint FKaotbvffphusp2xibg54y1807c foreign key (dataset_version_id) references datasetversion;
alter table keyvalue add constraint FKs8b954cb584lfhxvpfqufp00c foreign key (experiment_id) references experiment;
alter table keyvalue add constraint FKdd3gul9rqi1nwo1ue8dnjkloi foreign key (experiment_run_id) references experimentRun;
alter table keyvalue add constraint FK1j6qxx2f4tu0vhk6ncoigcer1 foreign key (job_id) references job;
alter table keyvalue add constraint FK4kpjcj5k42wy7jixlaw69t39e foreign key (project_id) references project;
alter table observation add constraint FKqukq600uk7ow0smk86lbecm16 foreign key (artifact_id) references artifact;
alter table observation add constraint FKlphf7x2yos9jxj1dafev0woqp foreign key (experiment_id) references experiment;
alter table observation add constraint FKrtaesogbnqbnfcg4r9oug3b5p foreign key (experiment_run_id) references experimentRun;
alter table observation add constraint FK3l830ric355y2m15auy29nugd foreign key (keyValueMapping_id) references keyvalue;
alter table observation add constraint FKtng8v4k62d498u95g3cly1dcp foreign key (project_id) references project;
alter table project add constraint FK7h4kclvrdgs3rp838yoj0utc4 foreign key (code_version_snapshot_id) references codeversion;
alter table query_parameter add constraint FK8ocpexp2jn9rqlf2loy36pwpu foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table TagMapping add constraint FKo3adl5c9mq66v4btyl9wwmbh foreign key (dataset_id) references dataset;
alter table TagMapping add constraint FKcsd9g3kgclunkjsigfn15pnl2 foreign key (dataset_version_id) references datasetversion;
alter table TagMapping add constraint FK6don0cq34v6j75a6ddvfft5mq foreign key (experiment_id) references experiment;
alter table TagMapping add constraint FK7qfxoshi1y5vnn42yvxklr7hm foreign key (experiment_run_id) references experimentRun;
alter table TagMapping add constraint FKht136fxcojwibhx48k7iolc1u foreign key (project_id) references project;
alter table user_comment add constraint FK8run8dgvadrrwcwe5xpdscynm foreign key (comment_id) references comment;
alter table artifact drop constraint FKb1510ajwbgmwqk9mk7s5madq8;
alter table artifact drop constraint FKkxd7ammk6wfh5sornvyqmwa6o;
alter table artifact drop constraint FKqi7jpmsvst8h67mvp18lrkdol;
alter table attribute drop constraint FKnt3ngg343dg4o7sven04h7tsx;
alter table attribute drop constraint FKc3dbivps61eg0k4pj8yvii3or;
alter table attribute drop constraint FKe0vuckk3jedm4r8aje7jiuqad;
alter table attribute drop constraint FKriiu1tqwndsykgh7mnmhx361v;
alter table attribute drop constraint FK2v3aix0o075acj0f29d38mewg;
alter table attribute drop constraint FK5kbo2i8a4hjtwrme7ii0q55xs;
alter table codeversion drop constraint FK52kol2q55s4ih48da63mshmua;
alter table codeversion drop constraint FKlmregkintq62cstaboy0b8mgv;
alter table collaboratorMappings drop constraint FKlysef6ksenp6fssh0gi7762u7;
alter table collaboratorMappings drop constraint FK6wxqhkm0t7jj81ra7cyo0ro67;
alter table dataset_part_info drop constraint FKglp4vghk1s78vudr9jnmvt7v2;
alter table datasetversion drop constraint FKqegkomuovtkr5iwqiqmav067;
alter table datasetversion drop constraint FK63372a2omdh2kx9bo7xifm13l;
alter table datasetversion drop constraint FK4axpq0odnw6n9yhom6kg0p0bw;
alter table experiment drop constraint FKabmp29pv19fw9g3rotaq4bqlk;
alter table experimentRun drop constraint FK155a2dpu2yc6kpbnf9bw9ej9e;
alter table Feature drop constraint FK1809dxglqgape7roab6ppb5pj;
alter table Feature drop constraint FK7npjb7lsh1lnc5sjfs5go1q9k;
alter table Feature drop constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc;
alter table Feature drop constraint FKiixqgx81l0gco5buvig6cqe2e;
alter table GitSnapshotEntity_filepaths drop constraint FKabgd4u299tnae1u81fnxtx4wg;
alter table keyvalue drop constraint FKe5e22km3s8b4v6fmd5agi1169;
alter table keyvalue drop constraint FKaotbvffphusp2xibg54y1807c;
alter table keyvalue drop constraint FKs8b954cb584lfhxvpfqufp00c;
alter table keyvalue drop constraint FKdd3gul9rqi1nwo1ue8dnjkloi;
alter table keyvalue drop constraint FK1j6qxx2f4tu0vhk6ncoigcer1;
alter table keyvalue drop constraint FK4kpjcj5k42wy7jixlaw69t39e;
alter table observation drop constraint FKqukq600uk7ow0smk86lbecm16;
alter table observation drop constraint FK4s2v1sw8hlvupyibjlhksbxu8;
alter table observation drop constraint FKlphf7x2yos9jxj1dafev0woqp;
alter table observation drop constraint FKrtaesogbnqbnfcg4r9oug3b5p;
alter table observation drop constraint FK3l830ric355y2m15auy29nugd;
alter table observation drop constraint FKtng8v4k62d498u95g3cly1dcp;
alter table project drop constraint FK7h4kclvrdgs3rp838yoj0utc4;
alter table query_parameter drop constraint FK8ocpexp2jn9rqlf2loy36pwpu;
alter table TagMapping drop constraint FKo3adl5c9mq66v4btyl9wwmbh;
alter table TagMapping drop constraint FKcsd9g3kgclunkjsigfn15pnl2;
alter table TagMapping drop constraint FK6don0cq34v6j75a6ddvfft5mq;
alter table TagMapping drop constraint FK7qfxoshi1y5vnn42yvxklr7hm;
alter table TagMapping drop constraint FKht136fxcojwibhx48k7iolc1u;
alter table user_comment drop constraint FK8run8dgvadrrwcwe5xpdscynm;
drop table if exists artifact cascade;
drop table if exists artifactStore cascade;
drop table if exists attribute cascade;
drop table if exists codeversion cascade;
drop table if exists collaborator cascade;
drop table if exists collaboratorMappings cascade;
drop table if exists comment cascade;
drop table if exists dataset cascade;
drop table if exists dataset_part_info cascade;
drop table if exists datasetversion cascade;
drop table if exists experiment cascade;
drop table if exists experimentRun cascade;
drop table if exists Feature cascade;
drop table if exists gitsnapshot cascade;
drop table if exists GitSnapshotEntity_filepaths cascade;
drop table if exists job cascade;
drop table if exists keyvalue cascade;
drop table if exists observation cascade;
drop table if exists path_dataset_version_info cascade;
drop table if exists project cascade;
drop table if exists query_dataset_version_info cascade;
drop table if exists query_parameter cascade;
drop table if exists raw_dataset_version_info cascade;
drop table if exists TagMapping cascade;
drop table if exists user_comment cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table artifact (id int8 not null, artifact_type int4, entity_name varchar(50), field_type varchar(50), filename_extension varchar(50), ar_key TEXT, linked_artifact_id varchar(255), ar_path TEXT, path_only boolean, store_type_path TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table artifactStore (id int8 not null, client_key TEXT, cloud_storage_file_path TEXT, cloud_storage_key TEXT, entity_id varchar(50), entity_name varchar(50), primary key (id));
create table attribute (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table codeversion (id int8 not null, date_logged int8, field_type varchar(50), code_archive_id int8, git_snapshot_id int8, primary key (id));
create table collaborator (verta_id varchar(255) not null, email_id varchar(255), share_via_type int4, user_id varchar(255), primary key (verta_id));
create table collaboratorMappings (id int8 not null, collaborator_type int4, date_created int8, date_deleted int8, date_updated int8, entity_id varchar(255), entity_name varchar(50), field_type varchar(50), message varchar(255), shared_by varchar(255), collaborator_id varchar(255), collaborator_verta_id varchar(255), primary key (id));
create table comment (id varchar(255) not null, entity_id varchar(255), entity_name varchar(255), primary key (id));
create table dataset (id varchar(255) not null, dataset_type int4, dataset_visibility int4, description TEXT, name varchar(255), owner varchar(255), time_created int8, time_updated int8, primary key (id));
create table dataset_part_info (id int8 not null, checksum varchar(255), entity_name varchar(50), field_type varchar(50), last_modified_at_source int8, path varchar(255), size int8, path_dataset_version_info_id int8, primary key (id));
create table datasetversion (id varchar(255) not null, dataset_id varchar(255), dataset_type int4, dataset_version_visibility int4, description TEXT, owner varchar(255), parent_id varchar(255), time_logged int8, time_updated int8, version int8, path_dataset_version_info_id int8, query_dataset_version_info_id int8, raw_dataset_version_info_id int8, primary key (id));
create table experiment (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_id varchar(255) not null, code_version_snapshot_id int8, primary key (id));
create table experimentRun (id varchar(255) not null, code_version varchar(255), date_created int8, date_updated int8, description TEXT, end_time int8, experiment_id varchar(255) not null, job_id varchar(255), name varchar(255), owner varchar(255), parent_id varchar(255), project_id varchar(255) not null, start_time int8, code_version_snapshot_id int8, primary key (id));
create table Feature (id int8 not null, entity_name varchar(50), feature TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), raw_dataset_version_info_id int8, primary key (id));
create table gitsnapshot (id int8 not null, field_type varchar(50), hash varchar(255), is_dirty int4, repo varchar(255), primary key (id));
create table GitSnapshotEntity_filepaths (GitSnapshotEntity_id int8 not null, filepaths varchar(255));
create table job (id varchar(255) not null, description TEXT, end_time varchar(255), job_status int4, job_type int4, owner varchar(255), start_time varchar(255), primary key (id));
create table keyvalue (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table observation (id int8 not null, entity_name varchar(50), field_type varchar(50), timestamp int8 not null, artifact_id int8, attributeMapping_id int8, experiment_id varchar(255), experiment_run_id varchar(255), keyValueMapping_id int8, project_id varchar(255), primary key (id));
create table path_dataset_version_info (id int8 not null, base_path varchar(255), field_type varchar(50), location_type int4, size int8, primary key (id));
create table project (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_visibility int4, readme_text TEXT, short_name varchar(255), code_version_snapshot_id int8, primary key (id));
create table query_dataset_version_info (id int8 not null, data_source_uri varchar(255), execution_timestamp int8, field_type varchar(50), num_records int8, query TEXT, query_template TEXT, primary key (id));
create table query_parameter (id int8 not null, entity_name varchar(50), field_type varchar(50), parameter_name TEXT, parameter_type int4, parameter_value TEXT, query_dataset_version_info_id int8, primary key (id));
create table raw_dataset_version_info (id int8 not null, checksum varchar(255), field_type varchar(50), num_records int8, object_path varchar(255), size int8, primary key (id));
create table TagMapping (id int8 not null, entity_name varchar(50), tags TEXT, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table user_comment (id varchar(255) not null, date_time int8, entity_name varchar(50), message varchar(255), owner varchar(255), user_id varchar(255), comment_id varchar(255), primary key (id));
alter table collaborator add constraint UK_knalm74v0noabmm15ya57ctbt unique (user_id);
alter table artifact add constraint FKb1510ajwbgmwqk9mk7s5madq8 foreign key (experiment_id) references experiment;
alter table artifact add constraint FKkxd7ammk6wfh5sornvyqmwa6o foreign key (experiment_run_id) references experimentRun;
alter table artifact add constraint FKqi7jpmsvst8h67mvp18lrkdol foreign key (project_id) references project;
alter table attribute add constraint FKnt3ngg343dg4o7sven04h7tsx foreign key (dataset_id) references dataset;
alter table attribute add constraint FKc3dbivps61eg0k4pj8yvii3or foreign key (dataset_version_id) references datasetversion;
alter table attribute add constraint FKe0vuckk3jedm4r8aje7jiuqad foreign key (experiment_id) references experiment;
alter table attribute add constraint FKriiu1tqwndsykgh7mnmhx361v foreign key (experiment_run_id) references experimentRun;
alter table attribute add constraint FK2v3aix0o075acj0f29d38mewg foreign key (job_id) references job;
alter table attribute add constraint FK5kbo2i8a4hjtwrme7ii0q55xs foreign key (project_id) references project;
alter table codeversion add constraint FK52kol2q55s4ih48da63mshmua foreign key (code_archive_id) references artifact;
alter table codeversion add constraint FKlmregkintq62cstaboy0b8mgv foreign key (git_snapshot_id) references gitsnapshot;
alter table collaboratorMappings add constraint FKlysef6ksenp6fssh0gi7762u7 foreign key (collaborator_id) references collaborator;
alter table collaboratorMappings add constraint FK6wxqhkm0t7jj81ra7cyo0ro67 foreign key (collaborator_verta_id) references collaborator;
alter table dataset_part_info add constraint FKglp4vghk1s78vudr9jnmvt7v2 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FKqegkomuovtkr5iwqiqmav067 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FK63372a2omdh2kx9bo7xifm13l foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table datasetversion add constraint FK4axpq0odnw6n9yhom6kg0p0bw foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table experiment add constraint FKabmp29pv19fw9g3rotaq4bqlk foreign key (code_version_snapshot_id) references codeversion;
alter table experimentRun add constraint FK155a2dpu2yc6kpbnf9bw9ej9e foreign key (code_version_snapshot_id) references codeversion;
alter table Feature add constraint FK1809dxglqgape7roab6ppb5pj foreign key (experiment_id) references experiment;
alter table Feature add constraint FK7npjb7lsh1lnc5sjfs5go1q9k foreign key (experiment_run_id) references experimentRun;
alter table Feature add constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc foreign key (project_id) references project;
alter table Feature add constraint FKiixqgx81l0gco5buvig6cqe2e foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table GitSnapshotEntity_filepaths add constraint FKabgd4u299tnae1u81fnxtx4wg foreign key (GitSnapshotEntity_id) references gitsnapshot;
alter table keyvalue add constraint FKe5e22km3s8b4v6fmd5agi1169 foreign key (dataset_id) references dataset;
alter table keyvalue add constraint FKaotbvffphusp2xibg54y1807c foreign key (dataset_version_id) references datasetversion;
alter table keyvalue add constraint FKs8b954cb584lfhxvpfqufp00c foreign key (experiment_id) references experiment;
alter table keyvalue add constraint FKdd3gul9rqi1nwo1ue8dnjkloi foreign key (experiment_run_id) references experimentRun;
alter table keyvalue add constraint FK1j6qxx2f4tu0vhk6ncoigcer1 foreign key (job_id) references job;
alter table keyvalue add constraint FK4kpjcj5k42wy7jixlaw69t39e foreign key (project_id) references project;
alter table observation add constraint FKqukq600uk7ow0smk86lbecm16 foreign key (artifact_id) references artifact;
alter table observation add constraint FK4s2v1sw8hlvupyibjlhksbxu8 foreign key (attributeMapping_id) references attribute;
alter table observation add constraint FKlphf7x2yos9jxj1dafev0woqp foreign key (experiment_id) references experiment;
alter table observation add constraint FKrtaesogbnqbnfcg4r9oug3b5p foreign key (experiment_run_id) references experimentRun;
alter table observation add constraint FK3l830ric355y2m15auy29nugd foreign key (keyValueMapping_id) references keyvalue;
alter table observation add constraint FKtng8v4k62d498u95g3cly1dcp foreign key (project_id) references project;
alter table project add constraint FK7h4kclvrdgs3rp838yoj0utc4 foreign key (code_version_snapshot_id) references codeversion;
alter table query_parameter add constraint FK8ocpexp2jn9rqlf2loy36pwpu foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table TagMapping add constraint FKo3adl5c9mq66v4btyl9wwmbh foreign key (dataset_id) references dataset;
alter table TagMapping add constraint FKcsd9g3kgclunkjsigfn15pnl2 foreign key (dataset_version_id) references datasetversion;
alter table TagMapping add constraint FK6don0cq34v6j75a6ddvfft5mq foreign key (experiment_id) references experiment;
alter table TagMapping add constraint FK7qfxoshi1y5vnn42yvxklr7hm foreign key (experiment_run_id) references experimentRun;
alter table TagMapping add constraint FKht136fxcojwibhx48k7iolc1u foreign key (project_id) references project;
alter table user_comment add constraint FK8run8dgvadrrwcwe5xpdscynm foreign key (comment_id) references comment;
alter table artifact drop constraint FKb1510ajwbgmwqk9mk7s5madq8;
alter table artifact drop constraint FKkxd7ammk6wfh5sornvyqmwa6o;
alter table artifact drop constraint FKqi7jpmsvst8h67mvp18lrkdol;
alter table attribute drop constraint FKnt3ngg343dg4o7sven04h7tsx;
alter table attribute drop constraint FKc3dbivps61eg0k4pj8yvii3or;
alter table attribute drop constraint FKe0vuckk3jedm4r8aje7jiuqad;
alter table attribute drop constraint FKriiu1tqwndsykgh7mnmhx361v;
alter table attribute drop constraint FK2v3aix0o075acj0f29d38mewg;
alter table attribute drop constraint FK5kbo2i8a4hjtwrme7ii0q55xs;
alter table codeversion drop constraint FK52kol2q55s4ih48da63mshmua;
alter table codeversion drop constraint FKlmregkintq62cstaboy0b8mgv;
alter table collaboratorMappings drop constraint FKlysef6ksenp6fssh0gi7762u7;
alter table collaboratorMappings drop constraint FK6wxqhkm0t7jj81ra7cyo0ro67;
alter table dataset_part_info drop constraint FKglp4vghk1s78vudr9jnmvt7v2;
alter table datasetversion drop constraint FKqegkomuovtkr5iwqiqmav067;
alter table datasetversion drop constraint FK63372a2omdh2kx9bo7xifm13l;
alter table datasetversion drop constraint FK4axpq0odnw6n9yhom6kg0p0bw;
alter table experiment drop constraint FKabmp29pv19fw9g3rotaq4bqlk;
alter table experimentRun drop constraint FK155a2dpu2yc6kpbnf9bw9ej9e;
alter table Feature drop constraint FK1809dxglqgape7roab6ppb5pj;
alter table Feature drop constraint FK7npjb7lsh1lnc5sjfs5go1q9k;
alter table Feature drop constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc;
alter table Feature drop constraint FKiixqgx81l0gco5buvig6cqe2e;
alter table GitSnapshotEntity_filepaths drop constraint FKabgd4u299tnae1u81fnxtx4wg;
alter table keyvalue drop constraint FKe5e22km3s8b4v6fmd5agi1169;
alter table keyvalue drop constraint FKaotbvffphusp2xibg54y1807c;
alter table keyvalue drop constraint FKs8b954cb584lfhxvpfqufp00c;
alter table keyvalue drop constraint FKdd3gul9rqi1nwo1ue8dnjkloi;
alter table keyvalue drop constraint FK1j6qxx2f4tu0vhk6ncoigcer1;
alter table keyvalue drop constraint FK4kpjcj5k42wy7jixlaw69t39e;
alter table observation drop constraint FKqukq600uk7ow0smk86lbecm16;
alter table observation drop constraint FKlphf7x2yos9jxj1dafev0woqp;
alter table observation drop constraint FKrtaesogbnqbnfcg4r9oug3b5p;
alter table observation drop constraint FK3l830ric355y2m15auy29nugd;
alter table observation drop constraint FKtng8v4k62d498u95g3cly1dcp;
alter table project drop constraint FK7h4kclvrdgs3rp838yoj0utc4;
alter table query_parameter drop constraint FK8ocpexp2jn9rqlf2loy36pwpu;
alter table TagMapping drop constraint FKo3adl5c9mq66v4btyl9wwmbh;
alter table TagMapping drop constraint FKcsd9g3kgclunkjsigfn15pnl2;
alter table TagMapping drop constraint FK6don0cq34v6j75a6ddvfft5mq;
alter table TagMapping drop constraint FK7qfxoshi1y5vnn42yvxklr7hm;
alter table TagMapping drop constraint FKht136fxcojwibhx48k7iolc1u;
alter table user_comment drop constraint FK8run8dgvadrrwcwe5xpdscynm;
drop table if exists artifact cascade;
drop table if exists artifactStore cascade;
drop table if exists attribute cascade;
drop table if exists codeversion cascade;
drop table if exists collaborator cascade;
drop table if exists collaboratorMappings cascade;
drop table if exists comment cascade;
drop table if exists dataset cascade;
drop table if exists dataset_part_info cascade;
drop table if exists datasetversion cascade;
drop table if exists experiment cascade;
drop table if exists experimentRun cascade;
drop table if exists Feature cascade;
drop table if exists gitsnapshot cascade;
drop table if exists GitSnapshotEntity_filepaths cascade;
drop table if exists job cascade;
drop table if exists keyvalue cascade;
drop table if exists observation cascade;
drop table if exists path_dataset_version_info cascade;
drop table if exists project cascade;
drop table if exists query_dataset_version_info cascade;
drop table if exists query_parameter cascade;
drop table if exists raw_dataset_version_info cascade;
drop table if exists TagMapping cascade;
drop table if exists user_comment cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table artifact (id int8 not null, artifact_type int4, entity_name varchar(50), field_type varchar(50), filename_extension varchar(50), ar_key TEXT, linked_artifact_id varchar(255), ar_path TEXT, path_only boolean, store_type_path TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table artifactStore (id int8 not null, client_key TEXT, cloud_storage_file_path TEXT, cloud_storage_key TEXT, entity_id varchar(50), entity_name varchar(50), primary key (id));
create table attribute (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table codeversion (id int8 not null, date_logged int8, field_type varchar(50), code_archive_id int8, git_snapshot_id int8, primary key (id));
create table collaborator (verta_id varchar(255) not null, email_id varchar(255), share_via_type int4, user_id varchar(255), primary key (verta_id));
create table collaboratorMappings (id int8 not null, collaborator_type int4, date_created int8, date_deleted int8, date_updated int8, entity_id varchar(255), entity_name varchar(50), field_type varchar(50), message varchar(255), shared_by varchar(255), collaborator_id varchar(255), collaborator_verta_id varchar(255), primary key (id));
create table comment (id varchar(255) not null, entity_id varchar(255), entity_name varchar(255), primary key (id));
create table dataset (id varchar(255) not null, dataset_type int4, dataset_visibility int4, description TEXT, name varchar(255), owner varchar(255), time_created int8, time_updated int8, primary key (id));
create table dataset_part_info (id int8 not null, checksum varchar(255), entity_name varchar(50), field_type varchar(50), last_modified_at_source int8, path varchar(255), size int8, path_dataset_version_info_id int8, primary key (id));
create table datasetversion (id varchar(255) not null, dataset_id varchar(255), dataset_type int4, dataset_version_visibility int4, description TEXT, owner varchar(255), parent_id varchar(255), time_logged int8, time_updated int8, version int8, path_dataset_version_info_id int8, query_dataset_version_info_id int8, raw_dataset_version_info_id int8, primary key (id));
create table experiment (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_id varchar(255) not null, code_version_snapshot_id int8, primary key (id));
create table experimentRun (id varchar(255) not null, code_version varchar(255), date_created int8, date_updated int8, description TEXT, end_time int8, experiment_id varchar(255) not null, job_id varchar(255), name varchar(255), owner varchar(255), parent_id varchar(255), project_id varchar(255) not null, start_time int8, code_version_snapshot_id int8, primary key (id));
create table Feature (id int8 not null, entity_name varchar(50), feature TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), raw_dataset_version_info_id int8, primary key (id));
create table gitsnapshot (id int8 not null, field_type varchar(50), hash varchar(255), is_dirty int4, repo varchar(255), primary key (id));
create table GitSnapshotEntity_filepaths (GitSnapshotEntity_id int8 not null, filepaths varchar(255));
create table job (id varchar(255) not null, description TEXT, end_time varchar(255), job_status int4, job_type int4, owner varchar(255), start_time varchar(255), primary key (id));
create table keyvalue (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table observation (id int8 not null, entity_name varchar(50), field_type varchar(50), timestamp int8 not null, artifact_id int8, experiment_id varchar(255), experiment_run_id varchar(255), keyValueMapping_id int8, project_id varchar(255), primary key (id));
create table path_dataset_version_info (id int8 not null, base_path varchar(255), field_type varchar(50), location_type int4, size int8, primary key (id));
create table project (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_visibility int4, readme_text TEXT, short_name varchar(255), code_version_snapshot_id int8, primary key (id));
create table query_dataset_version_info (id int8 not null, data_source_uri varchar(255), execution_timestamp int8, field_type varchar(50), num_records int8, query TEXT, query_template TEXT, primary key (id));
create table query_parameter (id int8 not null, entity_name varchar(50), field_type varchar(50), parameter_name TEXT, parameter_type int4, parameter_value TEXT, query_dataset_version_info_id int8, primary key (id));
create table raw_dataset_version_info (id int8 not null, checksum varchar(255), field_type varchar(50), num_records int8, object_path varchar(255), size int8, primary key (id));
create table TagMapping (id int8 not null, entity_name varchar(50), tags TEXT, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table user_comment (id varchar(255) not null, date_time int8, entity_name varchar(50), message varchar(255), owner varchar(255), user_id varchar(255), comment_id varchar(255), primary key (id));
alter table collaborator add constraint UK_knalm74v0noabmm15ya57ctbt unique (user_id);
alter table artifact add constraint FKb1510ajwbgmwqk9mk7s5madq8 foreign key (experiment_id) references experiment;
alter table artifact add constraint FKkxd7ammk6wfh5sornvyqmwa6o foreign key (experiment_run_id) references experimentRun;
alter table artifact add constraint FKqi7jpmsvst8h67mvp18lrkdol foreign key (project_id) references project;
alter table attribute add constraint FKnt3ngg343dg4o7sven04h7tsx foreign key (dataset_id) references dataset;
alter table attribute add constraint FKc3dbivps61eg0k4pj8yvii3or foreign key (dataset_version_id) references datasetversion;
alter table attribute add constraint FKe0vuckk3jedm4r8aje7jiuqad foreign key (experiment_id) references experiment;
alter table attribute add constraint FKriiu1tqwndsykgh7mnmhx361v foreign key (experiment_run_id) references experimentRun;
alter table attribute add constraint FK2v3aix0o075acj0f29d38mewg foreign key (job_id) references job;
alter table attribute add constraint FK5kbo2i8a4hjtwrme7ii0q55xs foreign key (project_id) references project;
alter table codeversion add constraint FK52kol2q55s4ih48da63mshmua foreign key (code_archive_id) references artifact;
alter table codeversion add constraint FKlmregkintq62cstaboy0b8mgv foreign key (git_snapshot_id) references gitsnapshot;
alter table collaboratorMappings add constraint FKlysef6ksenp6fssh0gi7762u7 foreign key (collaborator_id) references collaborator;
alter table collaboratorMappings add constraint FK6wxqhkm0t7jj81ra7cyo0ro67 foreign key (collaborator_verta_id) references collaborator;
alter table dataset_part_info add constraint FKglp4vghk1s78vudr9jnmvt7v2 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FKqegkomuovtkr5iwqiqmav067 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FK63372a2omdh2kx9bo7xifm13l foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table datasetversion add constraint FK4axpq0odnw6n9yhom6kg0p0bw foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table experiment add constraint FKabmp29pv19fw9g3rotaq4bqlk foreign key (code_version_snapshot_id) references codeversion;
alter table experimentRun add constraint FK155a2dpu2yc6kpbnf9bw9ej9e foreign key (code_version_snapshot_id) references codeversion;
alter table Feature add constraint FK1809dxglqgape7roab6ppb5pj foreign key (experiment_id) references experiment;
alter table Feature add constraint FK7npjb7lsh1lnc5sjfs5go1q9k foreign key (experiment_run_id) references experimentRun;
alter table Feature add constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc foreign key (project_id) references project;
alter table Feature add constraint FKiixqgx81l0gco5buvig6cqe2e foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table GitSnapshotEntity_filepaths add constraint FKabgd4u299tnae1u81fnxtx4wg foreign key (GitSnapshotEntity_id) references gitsnapshot;
alter table keyvalue add constraint FKe5e22km3s8b4v6fmd5agi1169 foreign key (dataset_id) references dataset;
alter table keyvalue add constraint FKaotbvffphusp2xibg54y1807c foreign key (dataset_version_id) references datasetversion;
alter table keyvalue add constraint FKs8b954cb584lfhxvpfqufp00c foreign key (experiment_id) references experiment;
alter table keyvalue add constraint FKdd3gul9rqi1nwo1ue8dnjkloi foreign key (experiment_run_id) references experimentRun;
alter table keyvalue add constraint FK1j6qxx2f4tu0vhk6ncoigcer1 foreign key (job_id) references job;
alter table keyvalue add constraint FK4kpjcj5k42wy7jixlaw69t39e foreign key (project_id) references project;
alter table observation add constraint FKqukq600uk7ow0smk86lbecm16 foreign key (artifact_id) references artifact;
alter table observation add constraint FKlphf7x2yos9jxj1dafev0woqp foreign key (experiment_id) references experiment;
alter table observation add constraint FKrtaesogbnqbnfcg4r9oug3b5p foreign key (experiment_run_id) references experimentRun;
alter table observation add constraint FK3l830ric355y2m15auy29nugd foreign key (keyValueMapping_id) references keyvalue;
alter table observation add constraint FKtng8v4k62d498u95g3cly1dcp foreign key (project_id) references project;
alter table project add constraint FK7h4kclvrdgs3rp838yoj0utc4 foreign key (code_version_snapshot_id) references codeversion;
alter table query_parameter add constraint FK8ocpexp2jn9rqlf2loy36pwpu foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table TagMapping add constraint FKo3adl5c9mq66v4btyl9wwmbh foreign key (dataset_id) references dataset;
alter table TagMapping add constraint FKcsd9g3kgclunkjsigfn15pnl2 foreign key (dataset_version_id) references datasetversion;
alter table TagMapping add constraint FK6don0cq34v6j75a6ddvfft5mq foreign key (experiment_id) references experiment;
alter table TagMapping add constraint FK7qfxoshi1y5vnn42yvxklr7hm foreign key (experiment_run_id) references experimentRun;
alter table TagMapping add constraint FKht136fxcojwibhx48k7iolc1u foreign key (project_id) references project;
alter table user_comment add constraint FK8run8dgvadrrwcwe5xpdscynm foreign key (comment_id) references comment;
alter table artifact drop constraint FKb1510ajwbgmwqk9mk7s5madq8;
alter table artifact drop constraint FKkxd7ammk6wfh5sornvyqmwa6o;
alter table artifact drop constraint FKqi7jpmsvst8h67mvp18lrkdol;
alter table attribute drop constraint FKnt3ngg343dg4o7sven04h7tsx;
alter table attribute drop constraint FKc3dbivps61eg0k4pj8yvii3or;
alter table attribute drop constraint FKe0vuckk3jedm4r8aje7jiuqad;
alter table attribute drop constraint FKriiu1tqwndsykgh7mnmhx361v;
alter table attribute drop constraint FK2v3aix0o075acj0f29d38mewg;
alter table attribute drop constraint FK5kbo2i8a4hjtwrme7ii0q55xs;
alter table codeversion drop constraint FK52kol2q55s4ih48da63mshmua;
alter table codeversion drop constraint FKlmregkintq62cstaboy0b8mgv;
alter table collaboratorMappings drop constraint FKlysef6ksenp6fssh0gi7762u7;
alter table collaboratorMappings drop constraint FK6wxqhkm0t7jj81ra7cyo0ro67;
alter table dataset_part_info drop constraint FKglp4vghk1s78vudr9jnmvt7v2;
alter table datasetversion drop constraint FKqegkomuovtkr5iwqiqmav067;
alter table datasetversion drop constraint FK63372a2omdh2kx9bo7xifm13l;
alter table datasetversion drop constraint FK4axpq0odnw6n9yhom6kg0p0bw;
alter table experiment drop constraint FKabmp29pv19fw9g3rotaq4bqlk;
alter table experimentRun drop constraint FK155a2dpu2yc6kpbnf9bw9ej9e;
alter table Feature drop constraint FK1809dxglqgape7roab6ppb5pj;
alter table Feature drop constraint FK7npjb7lsh1lnc5sjfs5go1q9k;
alter table Feature drop constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc;
alter table Feature drop constraint FKiixqgx81l0gco5buvig6cqe2e;
alter table GitSnapshotEntity_filepaths drop constraint FKabgd4u299tnae1u81fnxtx4wg;
alter table keyvalue drop constraint FKe5e22km3s8b4v6fmd5agi1169;
alter table keyvalue drop constraint FKaotbvffphusp2xibg54y1807c;
alter table keyvalue drop constraint FKs8b954cb584lfhxvpfqufp00c;
alter table keyvalue drop constraint FKdd3gul9rqi1nwo1ue8dnjkloi;
alter table keyvalue drop constraint FK1j6qxx2f4tu0vhk6ncoigcer1;
alter table keyvalue drop constraint FK4kpjcj5k42wy7jixlaw69t39e;
alter table observation drop constraint FKqukq600uk7ow0smk86lbecm16;
alter table observation drop constraint FKlphf7x2yos9jxj1dafev0woqp;
alter table observation drop constraint FKrtaesogbnqbnfcg4r9oug3b5p;
alter table observation drop constraint FK3l830ric355y2m15auy29nugd;
alter table observation drop constraint FKtng8v4k62d498u95g3cly1dcp;
alter table project drop constraint FK7h4kclvrdgs3rp838yoj0utc4;
alter table query_parameter drop constraint FK8ocpexp2jn9rqlf2loy36pwpu;
alter table TagMapping drop constraint FKo3adl5c9mq66v4btyl9wwmbh;
alter table TagMapping drop constraint FKcsd9g3kgclunkjsigfn15pnl2;
alter table TagMapping drop constraint FK6don0cq34v6j75a6ddvfft5mq;
alter table TagMapping drop constraint FK7qfxoshi1y5vnn42yvxklr7hm;
alter table TagMapping drop constraint FKht136fxcojwibhx48k7iolc1u;
alter table user_comment drop constraint FK8run8dgvadrrwcwe5xpdscynm;
drop table if exists artifact cascade;
drop table if exists artifactStore cascade;
drop table if exists attribute cascade;
drop table if exists codeversion cascade;
drop table if exists collaborator cascade;
drop table if exists collaboratorMappings cascade;
drop table if exists comment cascade;
drop table if exists dataset cascade;
drop table if exists dataset_part_info cascade;
drop table if exists datasetversion cascade;
drop table if exists experiment cascade;
drop table if exists experimentRun cascade;
drop table if exists Feature cascade;
drop table if exists gitsnapshot cascade;
drop table if exists GitSnapshotEntity_filepaths cascade;
drop table if exists job cascade;
drop table if exists keyvalue cascade;
drop table if exists observation cascade;
drop table if exists path_dataset_version_info cascade;
drop table if exists project cascade;
drop table if exists query_dataset_version_info cascade;
drop table if exists query_parameter cascade;
drop table if exists raw_dataset_version_info cascade;
drop table if exists TagMapping cascade;
drop table if exists user_comment cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table artifact (id int8 not null, artifact_type int4, entity_name varchar(50), field_type varchar(50), filename_extension varchar(50), ar_key TEXT, linked_artifact_id varchar(255), ar_path TEXT, path_only boolean, store_type_path TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table artifactStore (id int8 not null, client_key TEXT, cloud_storage_file_path TEXT, cloud_storage_key TEXT, entity_id varchar(50), entity_name varchar(50), primary key (id));
create table attribute (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table codeversion (id int8 not null, date_logged int8, field_type varchar(50), code_archive_id int8, git_snapshot_id int8, primary key (id));
create table collaborator (verta_id varchar(255) not null, email_id varchar(255), share_via_type int4, user_id varchar(255), primary key (verta_id));
create table collaboratorMappings (id int8 not null, collaborator_type int4, date_created int8, date_deleted int8, date_updated int8, entity_id varchar(255), entity_name varchar(50), field_type varchar(50), message varchar(255), shared_by varchar(255), collaborator_id varchar(255), collaborator_verta_id varchar(255), primary key (id));
create table comment (id varchar(255) not null, entity_id varchar(255), entity_name varchar(255), primary key (id));
create table dataset (id varchar(255) not null, dataset_type int4, dataset_visibility int4, description TEXT, name varchar(255), owner varchar(255), time_created int8, time_updated int8, primary key (id));
create table dataset_part_info (id int8 not null, checksum varchar(255), entity_name varchar(50), field_type varchar(50), last_modified_at_source int8, path varchar(255), size int8, path_dataset_version_info_id int8, primary key (id));
create table datasetversion (id varchar(255) not null, dataset_id varchar(255), dataset_type int4, dataset_version_visibility int4, description TEXT, owner varchar(255), parent_id varchar(255), time_logged int8, time_updated int8, version int8, path_dataset_version_info_id int8, query_dataset_version_info_id int8, raw_dataset_version_info_id int8, primary key (id));
create table experiment (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_id varchar(255) not null, code_version_snapshot_id int8, primary key (id));
create table experimentRun (id varchar(255) not null, code_version varchar(255), date_created int8, date_updated int8, description TEXT, end_time int8, experiment_id varchar(255) not null, job_id varchar(255), name varchar(255), owner varchar(255), parent_id varchar(255), project_id varchar(255) not null, start_time int8, code_version_snapshot_id int8, primary key (id));
create table Feature (id int8 not null, entity_name varchar(50), feature TEXT, experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), raw_dataset_version_info_id int8, primary key (id));
create table gitsnapshot (id int8 not null, field_type varchar(50), hash varchar(255), is_dirty int4, repo varchar(255), primary key (id));
create table GitSnapshotEntity_filepaths (GitSnapshotEntity_id int8 not null, filepaths varchar(255));
create table job (id varchar(255) not null, description TEXT, end_time varchar(255), job_status int4, job_type int4, owner varchar(255), start_time varchar(255), primary key (id));
create table keyvalue (id int8 not null, entity_name varchar(50), field_type varchar(50), kv_key TEXT, kv_value TEXT, value_type int4, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), job_id varchar(255), project_id varchar(255), primary key (id));
create table observation (id int8 not null, entity_name varchar(50), field_type varchar(50), timestamp int8 not null, artifact_id int8, experiment_id varchar(255), experiment_run_id varchar(255), keyValueMapping_id int8, project_id varchar(255), primary key (id));
create table path_dataset_version_info (id int8 not null, base_path varchar(255), field_type varchar(50), location_type int4, size int8, primary key (id));
create table project (id varchar(255) not null, date_created int8, date_updated int8, description TEXT, name varchar(255), owner varchar(255), project_visibility int4, readme_text TEXT, short_name varchar(255), code_version_snapshot_id int8, primary key (id));
create table query_dataset_version_info (id int8 not null, data_source_uri varchar(255), execution_timestamp int8, field_type varchar(50), num_records int8, query TEXT, query_template TEXT, primary key (id));
create table query_parameter (id int8 not null, entity_name varchar(50), field_type varchar(50), parameter_name TEXT, parameter_type int4, parameter_value TEXT, query_dataset_version_info_id int8, primary key (id));
create table raw_dataset_version_info (id int8 not null, checksum varchar(255), field_type varchar(50), num_records int8, object_path varchar(255), size int8, primary key (id));
create table TagMapping (id int8 not null, entity_name varchar(50), tags TEXT, dataset_id varchar(255), dataset_version_id varchar(255), experiment_id varchar(255), experiment_run_id varchar(255), project_id varchar(255), primary key (id));
create table user_comment (id varchar(255) not null, date_time int8, entity_name varchar(50), message varchar(255), owner varchar(255), user_id varchar(255), comment_id varchar(255), primary key (id));
alter table collaborator add constraint UK_knalm74v0noabmm15ya57ctbt unique (user_id);
alter table artifact add constraint FKb1510ajwbgmwqk9mk7s5madq8 foreign key (experiment_id) references experiment;
alter table artifact add constraint FKkxd7ammk6wfh5sornvyqmwa6o foreign key (experiment_run_id) references experimentRun;
alter table artifact add constraint FKqi7jpmsvst8h67mvp18lrkdol foreign key (project_id) references project;
alter table attribute add constraint FKnt3ngg343dg4o7sven04h7tsx foreign key (dataset_id) references dataset;
alter table attribute add constraint FKc3dbivps61eg0k4pj8yvii3or foreign key (dataset_version_id) references datasetversion;
alter table attribute add constraint FKe0vuckk3jedm4r8aje7jiuqad foreign key (experiment_id) references experiment;
alter table attribute add constraint FKriiu1tqwndsykgh7mnmhx361v foreign key (experiment_run_id) references experimentRun;
alter table attribute add constraint FK2v3aix0o075acj0f29d38mewg foreign key (job_id) references job;
alter table attribute add constraint FK5kbo2i8a4hjtwrme7ii0q55xs foreign key (project_id) references project;
alter table codeversion add constraint FK52kol2q55s4ih48da63mshmua foreign key (code_archive_id) references artifact;
alter table codeversion add constraint FKlmregkintq62cstaboy0b8mgv foreign key (git_snapshot_id) references gitsnapshot;
alter table collaboratorMappings add constraint FKlysef6ksenp6fssh0gi7762u7 foreign key (collaborator_id) references collaborator;
alter table collaboratorMappings add constraint FK6wxqhkm0t7jj81ra7cyo0ro67 foreign key (collaborator_verta_id) references collaborator;
alter table dataset_part_info add constraint FKglp4vghk1s78vudr9jnmvt7v2 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FKqegkomuovtkr5iwqiqmav067 foreign key (path_dataset_version_info_id) references path_dataset_version_info;
alter table datasetversion add constraint FK63372a2omdh2kx9bo7xifm13l foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table datasetversion add constraint FK4axpq0odnw6n9yhom6kg0p0bw foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table experiment add constraint FKabmp29pv19fw9g3rotaq4bqlk foreign key (code_version_snapshot_id) references codeversion;
alter table experimentRun add constraint FK155a2dpu2yc6kpbnf9bw9ej9e foreign key (code_version_snapshot_id) references codeversion;
alter table Feature add constraint FK1809dxglqgape7roab6ppb5pj foreign key (experiment_id) references experiment;
alter table Feature add constraint FK7npjb7lsh1lnc5sjfs5go1q9k foreign key (experiment_run_id) references experimentRun;
alter table Feature add constraint FK3tpwqa4p3gkvtbm5y8x7pl6bc foreign key (project_id) references project;
alter table Feature add constraint FKiixqgx81l0gco5buvig6cqe2e foreign key (raw_dataset_version_info_id) references raw_dataset_version_info;
alter table GitSnapshotEntity_filepaths add constraint FKabgd4u299tnae1u81fnxtx4wg foreign key (GitSnapshotEntity_id) references gitsnapshot;
alter table keyvalue add constraint FKe5e22km3s8b4v6fmd5agi1169 foreign key (dataset_id) references dataset;
alter table keyvalue add constraint FKaotbvffphusp2xibg54y1807c foreign key (dataset_version_id) references datasetversion;
alter table keyvalue add constraint FKs8b954cb584lfhxvpfqufp00c foreign key (experiment_id) references experiment;
alter table keyvalue add constraint FKdd3gul9rqi1nwo1ue8dnjkloi foreign key (experiment_run_id) references experimentRun;
alter table keyvalue add constraint FK1j6qxx2f4tu0vhk6ncoigcer1 foreign key (job_id) references job;
alter table keyvalue add constraint FK4kpjcj5k42wy7jixlaw69t39e foreign key (project_id) references project;
alter table observation add constraint FKqukq600uk7ow0smk86lbecm16 foreign key (artifact_id) references artifact;
alter table observation add constraint FKlphf7x2yos9jxj1dafev0woqp foreign key (experiment_id) references experiment;
alter table observation add constraint FKrtaesogbnqbnfcg4r9oug3b5p foreign key (experiment_run_id) references experimentRun;
alter table observation add constraint FK3l830ric355y2m15auy29nugd foreign key (keyValueMapping_id) references keyvalue;
alter table observation add constraint FKtng8v4k62d498u95g3cly1dcp foreign key (project_id) references project;
alter table project add constraint FK7h4kclvrdgs3rp838yoj0utc4 foreign key (code_version_snapshot_id) references codeversion;
alter table query_parameter add constraint FK8ocpexp2jn9rqlf2loy36pwpu foreign key (query_dataset_version_info_id) references query_dataset_version_info;
alter table TagMapping add constraint FKo3adl5c9mq66v4btyl9wwmbh foreign key (dataset_id) references dataset;
alter table TagMapping add constraint FKcsd9g3kgclunkjsigfn15pnl2 foreign key (dataset_version_id) references datasetversion;
alter table TagMapping add constraint FK6don0cq34v6j75a6ddvfft5mq foreign key (experiment_id) references experiment;
alter table TagMapping add constraint FK7qfxoshi1y5vnn42yvxklr7hm foreign key (experiment_run_id) references experimentRun;
alter table TagMapping add constraint FKht136fxcojwibhx48k7iolc1u foreign key (project_id) references project;
alter table user_comment add constraint FK8run8dgvadrrwcwe5xpdscynm foreign key (comment_id) references comment;
