// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.Function3;
import ai.verta.modeldb.versioning.blob.diff.*;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.generator.java.util.*;
import com.pholser.junit.quickcheck.random.*;

public class AutogenGitCodeDiffGen extends Generator<AutogenGitCodeDiff> {
  public AutogenGitCodeDiffGen() {
    super(AutogenGitCodeDiff.class);
  }

  @Override
  public AutogenGitCodeDiff generate(SourceOfRandomness r, GenerationStatus status) {
    // if (r.nextBoolean())
    //     return null;

    AutogenGitCodeDiff obj = new AutogenGitCodeDiff();
    if (r.nextBoolean()) {
      obj.setA(Utils.removeEmpty(gen().type(AutogenGitCodeBlob.class).generate(r, status)));
    }
    if (r.nextBoolean()) {
      obj.setB(Utils.removeEmpty(gen().type(AutogenGitCodeBlob.class).generate(r, status)));
    }
    if (r.nextBoolean()) {
      obj.setStatus(
          Utils.removeEmpty(gen().type(AutogenDiffStatusEnumDiffStatus.class).generate(r, status)));
    }
    return obj;
  }
}
