// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.Function3;
import ai.verta.modeldb.versioning.blob.diff.*;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.generator.java.util.*;
import com.pholser.junit.quickcheck.random.*;

public class AutogenHyperparameterSetConfigBlobGen extends Generator<AutogenHyperparameterSetConfigBlob> {
    public AutogenHyperparameterSetConfigBlobGen() {
        super(AutogenHyperparameterSetConfigBlob.class);
    }

    @Override public AutogenHyperparameterSetConfigBlob generate(
            SourceOfRandomness r,
            GenerationStatus status) {
                // if (r.nextBoolean())
                //     return null;

                AutogenHyperparameterSetConfigBlob obj = new AutogenHyperparameterSetConfigBlob();
                if (r.nextBoolean()) {
                    obj.setContinuous(Utils.removeEmpty(gen().type(AutogenContinuousHyperparameterSetConfigBlob
.class).generate(r, status)));
                }
                if (r.nextBoolean()) {
                    obj.setDiscrete(Utils.removeEmpty(gen().type(AutogenDiscreteHyperparameterSetConfigBlob
.class).generate(r, status)));
                }
                if (r.nextBoolean()) {
                    obj.setName(Utils.removeEmpty(new StringGenerator().generate(r, status)));
                }
                return obj;
    }
}
