// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.Function3;
import ai.verta.modeldb.versioning.blob.diff.*;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.generator.java.util.*;
import com.pholser.junit.quickcheck.random.*;

public class AutogenDiffStatusEnumDiffStatusGen extends Generator<AutogenDiffStatusEnumDiffStatus> {
  public AutogenDiffStatusEnumDiffStatusGen() {
    super(AutogenDiffStatusEnumDiffStatus.class);
  }

  @Override
  public AutogenDiffStatusEnumDiffStatus generate(SourceOfRandomness r, GenerationStatus status) {
    return new AutogenDiffStatusEnumDiffStatus(
        r.choose(
            new DiffStatusEnum.DiffStatus[] {
              DiffStatusEnum.DiffStatus.ADDED,
              DiffStatusEnum.DiffStatus.DELETED,
              DiffStatusEnum.DiffStatus.MODIFIED
            }));
  }
}
