// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;

public class CodeDiff {
    public GitCodeDiff Git;
    public NotebookCodeDiff Notebook;

    public CodeDiff() {
        this.Git = null;
        this.Notebook = null;
    }

    public CodeDiff setGit(GitCodeDiff value) {
        this.Git = value;
        return this;
    }
    public CodeDiff setNotebook(NotebookCodeDiff value) {
        this.Notebook = value;
        return this;
    }

    static public CodeDiff fromProto(ai.verta.modeldb.versioning.CodeDiff blob) {
        CodeDiff obj = new CodeDiff();
        {
            Function<Void,GitCodeDiff> f = x -> GitCodeDiff.fromProto(blob.getGit());
            if (f != null) {
                obj.Git = f.apply(null);
            }
        }
        {
            Function<Void,NotebookCodeDiff> f = x -> NotebookCodeDiff.fromProto(blob.getNotebook());
            if (f != null) {
                obj.Notebook = f.apply(null);
            }
        }
        return obj;
    }

    public void preVisitShallow(Visitor visitor) throws ModelDBException {
        visitor.preVisit(this);
    }

    public void preVisitDeep(Visitor visitor) throws ModelDBException {
        this.preVisitShallow(visitor);
        {
            Function<GitCodeDiff,Void> f = v -> {v.preVisitDeep(visitor); return null;};
            if (f != null) {
                f.apply(this.Git);
            }
        }
        {
            Function<NotebookCodeDiff,Void> f = v -> {v.preVisitDeep(visitor); return null;};
            if (f != null) {
                f.apply(this.Notebook);
            }
        }
    }

    public CodeDiff postVisitShallow(Visitor visitor) throws ModelDBException {
        return visitor.postVisit(this);
    }

    public CodeDiff postVisitDeep(Visitor visitor) throws ModelDBException {
        {
            Function<GitCodeDiff,GitCodeDiff> f = v -> v.postVisitDeep(visitor);
            if (f != null) {
                this.Git = f.apply(this.Git);
            }
        }
        {
            Function<NotebookCodeDiff,NotebookCodeDiff> f = v -> v.postVisitDeep(visitor);
            if (f != null) {
                this.Notebook = f.apply(this.Notebook);
            }
        }
        return this.postVisitShallow(visitor);
    }
}
