// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.*;
import ai.verta.modeldb.versioning.blob.diff.Function3;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;
import java.util.*;
import java.util.function.Function;

public class CodeDiff implements ProtoType {
  public Optional<GitCodeDiff> Git;
  public Optional<NotebookCodeDiff> Notebook;

  public CodeDiff() {
    this.Git = Optional.empty();
    this.Notebook = Optional.empty();
  }

  public Boolean isEmpty() {
    if (this.Git.isPresent()) {
      return false;
    }
    if (this.Notebook.isPresent()) {
      return false;
    }
    return true;
  }

  // TODO: not consider order on lists
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null) return false;
    if (!(o instanceof CodeDiff)) return false;
    CodeDiff other = (CodeDiff) o;

    {
      Function3<GitCodeDiff, GitCodeDiff, Boolean> f = (x, y) -> x.equals(y);
      if (this.Git.isPresent() || other.Git.isPresent()) {
        if (!this.Git.isPresent()) return false;
        if (other.Git.isPresent()) return false;
        if (!f.apply(this.Git.get(), other.Git.get())) return false;
      }
    }
    {
      Function3<NotebookCodeDiff, NotebookCodeDiff, Boolean> f = (x, y) -> x.equals(y);
      if (this.Notebook.isPresent() || other.Notebook.isPresent()) {
        if (!this.Notebook.isPresent()) return false;
        if (other.Notebook.isPresent()) return false;
        if (!f.apply(this.Notebook.get(), other.Notebook.get())) return false;
      }
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.Git, this.Notebook);
  }

  public CodeDiff setGit(Optional<GitCodeDiff> value) {
    this.Git = value;
    return this;
  }

  public CodeDiff setGit(GitCodeDiff value) {
    if (value == null) this.Git = Optional.empty();
    else this.Git = Optional.of(value);
    return this;
  }

  public CodeDiff setNotebook(Optional<NotebookCodeDiff> value) {
    this.Notebook = value;
    return this;
  }

  public CodeDiff setNotebook(NotebookCodeDiff value) {
    if (value == null) this.Notebook = Optional.empty();
    else this.Notebook = Optional.of(value);
    return this;
  }

  public static CodeDiff fromProto(ai.verta.modeldb.versioning.CodeDiff blob) {
    if (blob == null) {
      return null;
    }

    CodeDiff obj = new CodeDiff();
    {
      Function<ai.verta.modeldb.versioning.CodeDiff, GitCodeDiff> f =
          x -> GitCodeDiff.fromProto(blob.getGit());
      obj.Git = Utils.removeEmpty(f.apply(blob));
    }
    {
      Function<ai.verta.modeldb.versioning.CodeDiff, NotebookCodeDiff> f =
          x -> NotebookCodeDiff.fromProto(blob.getNotebook());
      obj.Notebook = Utils.removeEmpty(f.apply(blob));
    }
    return obj;
  }

  public ai.verta.modeldb.versioning.CodeDiff.Builder toProto() {
    ai.verta.modeldb.versioning.CodeDiff.Builder builder =
        ai.verta.modeldb.versioning.CodeDiff.newBuilder();
    this.Git.ifPresent(x -> builder.setGit(x.toProto()));
    this.Notebook.ifPresent(x -> builder.setNotebook(x.toProto()));
    return builder;
  }

  public void preVisitShallow(Visitor visitor) throws ModelDBException {
    visitor.preVisitCodeDiff(this);
  }

  public void preVisitDeep(Visitor visitor) throws ModelDBException {
    this.preVisitShallow(visitor);
    if (this.Git.isPresent()) visitor.preVisitDeepGitCodeDiff(this.Git.get());
    if (this.Notebook.isPresent()) visitor.preVisitDeepNotebookCodeDiff(this.Notebook.get());
  }

  public CodeDiff postVisitShallow(Visitor visitor) throws ModelDBException {
    return visitor.postVisitCodeDiff(this);
  }

  public CodeDiff postVisitDeep(Visitor visitor) throws ModelDBException {
    if (this.Git.isPresent()) this.setGit(visitor.postVisitDeepGitCodeDiff(this.Git.get()));
    if (this.Notebook.isPresent())
      this.setNotebook(visitor.postVisitDeepNotebookCodeDiff(this.Notebook.get()));
    return this.postVisitShallow(visitor);
  }
}
