// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.*;
import ai.verta.modeldb.versioning.blob.diff.Function3;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class CommandLineEnvironmentDiff implements ProtoType {
  public Optional<DiffStatusEnumDiffStatus> Status;
  public Optional<List<String>> A;
  public Optional<List<String>> B;

  public CommandLineEnvironmentDiff() {
    this.Status = Optional.empty();
    this.A = Optional.empty();
    this.B = Optional.empty();
  }

  public Boolean isEmpty() {
    if (this.Status.isPresent()) {
      return false;
    }
    if (this.A.isPresent()) {
      return false;
    }
    if (this.B.isPresent()) {
      return false;
    }
    return true;
  }

  // TODO: not consider order on lists
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null) return false;
    if (!(o instanceof CommandLineEnvironmentDiff)) return false;
    CommandLineEnvironmentDiff other = (CommandLineEnvironmentDiff) o;

    {
      Function3<DiffStatusEnumDiffStatus, DiffStatusEnumDiffStatus, Boolean> f =
          (x, y) -> x.equals(y);
      if (this.Status.isPresent() || other.Status.isPresent()) {
        if (!this.Status.isPresent()) return false;
        if (other.Status.isPresent()) return false;
        if (!f.apply(this.Status.get(), other.Status.get())) return false;
      }
    }
    {
      Function3<List<String>, List<String>, Boolean> f =
          (x2, y2) ->
              IntStream.range(0, Math.min(x2.size(), y2.size()))
                  .mapToObj(
                      i -> {
                        Function3<String, String, Boolean> f2 = (x, y) -> x.equals(y);
                        return f2.apply(x2.get(i), y2.get(i));
                      })
                  .filter(x -> x != null)
                  .collect(Collectors.toList())
                  .isEmpty();
      if (this.A.isPresent() || other.A.isPresent()) {
        if (!this.A.isPresent()) return false;
        if (other.A.isPresent()) return false;
        if (!f.apply(this.A.get(), other.A.get())) return false;
      }
    }
    {
      Function3<List<String>, List<String>, Boolean> f =
          (x2, y2) ->
              IntStream.range(0, Math.min(x2.size(), y2.size()))
                  .mapToObj(
                      i -> {
                        Function3<String, String, Boolean> f2 = (x, y) -> x.equals(y);
                        return f2.apply(x2.get(i), y2.get(i));
                      })
                  .filter(x -> x != null)
                  .collect(Collectors.toList())
                  .isEmpty();
      if (this.B.isPresent() || other.B.isPresent()) {
        if (!this.B.isPresent()) return false;
        if (other.B.isPresent()) return false;
        if (!f.apply(this.B.get(), other.B.get())) return false;
      }
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.Status, this.A, this.B);
  }

  public CommandLineEnvironmentDiff setStatus(Optional<DiffStatusEnumDiffStatus> value) {
    this.Status = value;
    return this;
  }

  public CommandLineEnvironmentDiff setStatus(DiffStatusEnumDiffStatus value) {
    if (value == null) this.Status = Optional.empty();
    else this.Status = Optional.of(value);
    return this;
  }

  public CommandLineEnvironmentDiff setA(Optional<List<String>> value) {
    this.A = value;
    return this;
  }

  public CommandLineEnvironmentDiff setA(List<String> value) {
    if (value == null) this.A = Optional.empty();
    else this.A = Optional.of(value);
    return this;
  }

  public CommandLineEnvironmentDiff setB(Optional<List<String>> value) {
    this.B = value;
    return this;
  }

  public CommandLineEnvironmentDiff setB(List<String> value) {
    if (value == null) this.B = Optional.empty();
    else this.B = Optional.of(value);
    return this;
  }

  public static CommandLineEnvironmentDiff fromProto(
      ai.verta.modeldb.versioning.CommandLineEnvironmentDiff blob) {
    if (blob == null) {
      return null;
    }

    CommandLineEnvironmentDiff obj = new CommandLineEnvironmentDiff();
    {
      Function<ai.verta.modeldb.versioning.CommandLineEnvironmentDiff, DiffStatusEnumDiffStatus> f =
          x -> DiffStatusEnumDiffStatus.fromProto(blob.getStatus());
      obj.Status = Utils.removeEmpty(f.apply(blob));
    }
    {
      Function<ai.verta.modeldb.versioning.CommandLineEnvironmentDiff, List<String>> f =
          x -> blob.getAList();
      obj.A = Utils.removeEmpty(f.apply(blob));
    }
    {
      Function<ai.verta.modeldb.versioning.CommandLineEnvironmentDiff, List<String>> f =
          x -> blob.getBList();
      obj.B = Utils.removeEmpty(f.apply(blob));
    }
    return obj;
  }

  public ai.verta.modeldb.versioning.CommandLineEnvironmentDiff.Builder toProto() {
    ai.verta.modeldb.versioning.CommandLineEnvironmentDiff.Builder builder =
        ai.verta.modeldb.versioning.CommandLineEnvironmentDiff.newBuilder();
    this.Status.ifPresent(x -> builder.setStatus(x.toProto()));
    this.A.ifPresent(x -> builder.addAllA(x));
    this.B.ifPresent(x -> builder.addAllB(x));
    return builder;
  }

  public void preVisitShallow(Visitor visitor) throws ModelDBException {
    visitor.preVisitCommandLineEnvironmentDiff(this);
  }

  public void preVisitDeep(Visitor visitor) throws ModelDBException {
    this.preVisitShallow(visitor);
    if (this.Status.isPresent()) visitor.preVisitDeepDiffStatusEnumDiffStatus(this.Status.get());
    if (this.A.isPresent()) visitor.preVisitDeepListOfString(this.A.get());
    if (this.B.isPresent()) visitor.preVisitDeepListOfString(this.B.get());
  }

  public CommandLineEnvironmentDiff postVisitShallow(Visitor visitor) throws ModelDBException {
    return visitor.postVisitCommandLineEnvironmentDiff(this);
  }

  public CommandLineEnvironmentDiff postVisitDeep(Visitor visitor) throws ModelDBException {
    if (this.Status.isPresent())
      this.setStatus(visitor.postVisitDeepDiffStatusEnumDiffStatus(this.Status.get()));
    if (this.A.isPresent()) this.setA(visitor.postVisitDeepListOfString(this.A.get()));
    if (this.B.isPresent()) this.setB(visitor.postVisitDeepListOfString(this.B.get()));
    return this.postVisitShallow(visitor);
  }
}
