// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.*;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.generator.java.util.*;
import com.pholser.junit.quickcheck.random.*;
import java.util.*;

public class ConfigBlobGen extends Generator<ConfigBlob> {
  public ConfigBlobGen() {
    super(ConfigBlob.class);
  }

  @Override
  public ConfigBlob generate(SourceOfRandomness r, GenerationStatus status) {
    // if (r.nextBoolean())
    //     return null;

    ConfigBlob obj = new ConfigBlob();
    if (r.nextBoolean()) {
      int size = r.nextInt(0, 10);
      List<HyperparameterSetConfigBlob> ret = new ArrayList(size);
      for (int i = 0; i < size; i++) {
        ret.add(gen().type(HyperparameterSetConfigBlob.class).generate(r, status));
      }
      obj.setHyperparameterSet(Utils.removeEmpty(ret));
    }
    if (r.nextBoolean()) {
      int size = r.nextInt(0, 10);
      List<HyperparameterConfigBlob> ret = new ArrayList(size);
      for (int i = 0; i < size; i++) {
        ret.add(gen().type(HyperparameterConfigBlob.class).generate(r, status));
      }
      obj.setHyperparameters(Utils.removeEmpty(ret));
    }
    return obj;
  }
}
