// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import ai.verta.modeldb.ModelDBException;
import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.*;
import ai.verta.modeldb.versioning.blob.diff.Function3;
import ai.verta.modeldb.versioning.blob.visitors.Visitor;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.random.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.util.function.Function;
import org.apache.commons.codec.binary.Hex;

public class S3DatasetComponentBlob implements ProtoType {
  public PathDatasetComponentBlob Path;

  public S3DatasetComponentBlob() {
    this.Path = null;
  }

  public Boolean isEmpty() {
    if (this.Path != null && !this.Path.equals(null)) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("{\"class\": \"S3DatasetComponentBlob\", \"fields\": {");
    boolean first = true;
    if (this.Path != null && !this.Path.equals(null)) {
      if (!first) sb.append(", ");
      sb.append("\"Path\": " + Path);
      first = false;
    }
    sb.append("}}");
    return sb.toString();
  }

  @Override
  public String getSHA() throws NoSuchAlgorithmException {
    StringBuilder sb = new StringBuilder();
    sb.append("S3DatasetComponentBlob");
    if (this.Path != null && !this.Path.equals(null)) {
      sb.append("::Path::").append(Path);
    }

    MessageDigest digest = MessageDigest.getInstance("SHA-256");
    byte[] hash = digest.digest(sb.toString().getBytes(StandardCharsets.UTF_8));
    return new String(new Hex().encode(hash));
  }

  // TODO: not consider order on lists
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null) return false;
    if (!(o instanceof S3DatasetComponentBlob)) return false;
    S3DatasetComponentBlob other = (S3DatasetComponentBlob) o;

    {
      Function3<PathDatasetComponentBlob, PathDatasetComponentBlob, Boolean> f =
          (x, y) -> x.equals(y);
      if (this.Path != null || other.Path != null) {
        if (this.Path == null && other.Path != null) return false;
        if (this.Path != null && other.Path == null) return false;
        if (!f.apply(this.Path, other.Path)) return false;
      }
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.Path);
  }

  public S3DatasetComponentBlob setPath(PathDatasetComponentBlob value) {
    this.Path = Utils.removeEmpty(value);
    return this;
  }

  public static S3DatasetComponentBlob fromProto(
      ai.verta.modeldb.versioning.S3DatasetComponentBlob blob) {
    if (blob == null) {
      return null;
    }

    S3DatasetComponentBlob obj = new S3DatasetComponentBlob();
    {
      Function<ai.verta.modeldb.versioning.S3DatasetComponentBlob, PathDatasetComponentBlob> f =
          x -> PathDatasetComponentBlob.fromProto(blob.getPath());
      obj.Path = Utils.removeEmpty(f.apply(blob));
    }
    return obj;
  }

  public ai.verta.modeldb.versioning.S3DatasetComponentBlob.Builder toProto() {
    ai.verta.modeldb.versioning.S3DatasetComponentBlob.Builder builder =
        ai.verta.modeldb.versioning.S3DatasetComponentBlob.newBuilder();
    {
      if (this.Path != null && !this.Path.equals(null)) {
        Function<ai.verta.modeldb.versioning.S3DatasetComponentBlob.Builder, Void> f =
            x -> {
              builder.setPath(this.Path.toProto());
              return null;
            };
        f.apply(builder);
      }
    }
    return builder;
  }

  public void preVisitShallow(Visitor visitor) throws ModelDBException {
    visitor.preVisitS3DatasetComponentBlob(this);
  }

  public void preVisitDeep(Visitor visitor) throws ModelDBException {
    this.preVisitShallow(visitor);
    visitor.preVisitDeepPathDatasetComponentBlob(this.Path);
  }

  public S3DatasetComponentBlob postVisitShallow(Visitor visitor) throws ModelDBException {
    return visitor.postVisitS3DatasetComponentBlob(this);
  }

  public S3DatasetComponentBlob postVisitDeep(Visitor visitor) throws ModelDBException {
    this.setPath(visitor.postVisitDeepPathDatasetComponentBlob(this.Path));
    return this.postVisitShallow(visitor);
  }
}
