// THIS FILE IS AUTO-GENERATED. DO NOT EDIT
package ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model;

import ai.verta.modeldb.versioning.*;
import ai.verta.modeldb.versioning.blob.diff.*;
import com.pholser.junit.quickcheck.generator.*;
import com.pholser.junit.quickcheck.generator.java.util.*;
import com.pholser.junit.quickcheck.random.*;
import java.util.*;

public class VersionEnvironmentDiffGen extends Generator<VersionEnvironmentDiff> {
  public VersionEnvironmentDiffGen() {
    super(VersionEnvironmentDiff.class);
  }

  @Override
  public VersionEnvironmentDiff generate(SourceOfRandomness r, GenerationStatus status) {
    // if (r.nextBoolean())
    //     return null;

    VersionEnvironmentDiff obj = new VersionEnvironmentDiff();
    if (r.nextBoolean()) {
      obj.setStatus(
          Utils.removeEmpty(gen().type(DiffStatusEnumDiffStatus.class).generate(r, status)));
    }
    if (r.nextBoolean()) {
      obj.setA(Utils.removeEmpty(gen().type(VersionEnvironmentBlob.class).generate(r, status)));
    }
    if (r.nextBoolean()) {
      obj.setB(Utils.removeEmpty(gen().type(VersionEnvironmentBlob.class).generate(r, status)));
    }
    return obj;
  }
}
