package ai.verta.modeldb.blobs;

import static org.junit.Assert.*;
import static org.junit.Assume.*;

import ai.verta.modeldb.versioning.autogenerated._public.modeldb.versioning.model.*;
import com.pholser.junit.quickcheck.Property;
import com.pholser.junit.quickcheck.runner.JUnitQuickcheck;
import org.junit.runner.RunWith;

@RunWith(JUnitQuickcheck.class)
public class BlobEquality {
  @Property
  public void equality(AutogenBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenBlobDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenCodeBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenCodeDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenCommandLineEnvironmentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenConfigBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenConfigDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenContinuousHyperparameterSetConfigBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenDatasetBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenDatasetDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenDiscreteHyperparameterSetConfigBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenDockerEnvironmentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenDockerEnvironmentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenEnvironmentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenEnvironmentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenEnvironmentVariablesBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenEnvironmentVariablesDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenGitCodeBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenGitCodeDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenHyperparameterConfigBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenHyperparameterConfigDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenHyperparameterSetConfigBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenHyperparameterSetConfigDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenHyperparameterValuesConfigBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenNotebookCodeBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenNotebookCodeDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPathDatasetBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPathDatasetComponentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPathDatasetComponentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPathDatasetDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPythonEnvironmentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPythonEnvironmentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPythonRequirementEnvironmentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenPythonRequirementEnvironmentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenS3DatasetBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenS3DatasetComponentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenS3DatasetComponentDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenS3DatasetDiff b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenVersionEnvironmentBlob b) {
    assertTrue(b.equals(b));
  }

  @Property
  public void equality(AutogenVersionEnvironmentDiff b) {
    assertTrue(b.equals(b));
  }
}
