image: vertaaiofficial/modeldb-graphql
imageTag: 2.0.8.1
tolerations: []
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi
env: {}
service:
  annotations: {}
affinity: {}
hpa:
  enabled: false
pdb:
  enabled: false
labels: {}
