# -*- coding: utf-8 -*-

HOST_ENV_VAR = "VERTA_HOST"
PORT_ENV_VAR = "VERTA_PORT"
EMAIL_ENV_VAR = "VERTA_EMAIL"
DEV_KEY_ENV_VAR = "VERTA_DEV_KEY"
EMAIL_2_ENV_VAR = "VERTA_EMAIL_2"
DEV_KEY_2_ENV_VAR = "VERTA_DEV_KEY_2"
EMAIL_3_ENV_VAR = "VERTA_EMAIL_3"
DEV_KEY_3_ENV_VAR = "VERTA_DEV_KEY_3"

DEFAULT_HOST = None
DEFAULT_PORT = None
DEFAULT_EMAIL = None
DEFAULT_DEV_KEY = None
