# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from ..uac import SCIMConfiguration_pb2 as uac_dot_SCIMConfiguration__pb2
from ..uac import UACService_pb2 as uac_dot_UACService__pb2


class SCIMConfigurationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getConfiguration = channel.unary_unary(
        '/ai.verta.uac.SCIMConfigurationService/getConfiguration',
        request_serializer=uac_dot_UACService__pb2.Empty.SerializeToString,
        response_deserializer=uac_dot_SCIMConfiguration__pb2.SCIMConfiguration.FromString,
        )


class SCIMConfigurationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getConfiguration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SCIMConfigurationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getConfiguration': grpc.unary_unary_rpc_method_handler(
          servicer.getConfiguration,
          request_deserializer=uac_dot_UACService__pb2.Empty.FromString,
          response_serializer=uac_dot_SCIMConfiguration__pb2.SCIMConfiguration.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ai.verta.uac.SCIMConfigurationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
