name: Python client unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - client/verta/verta/**.py
      - client/verta/tests/unit_tests/**.py
  push:
    branches:
      - main
      - "release/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/verta

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: python -m pip install '.[unit_tests]'

      - name: Run unit tests
        run: pytest tests/unit_tests
